// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: goods.proto

package goods

import (
	"context"

	"zeromall/goods/rpc/goodsPb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddGoodsReq           = goodsPb.AddGoodsReq
	AddGoodsResp          = goodsPb.AddGoodsResp
	AdminGoodsItem        = goodsPb.AdminGoodsItem
	AdminGoodsListReq     = goodsPb.AdminGoodsListReq
	AdminGoodsListResp    = goodsPb.AdminGoodsListResp
	BatchGetGoodsInfoReq  = goodsPb.BatchGetGoodsInfoReq
	BatchGetGoodsInfoResp = goodsPb.BatchGetGoodsInfoResp
	GoodsDetailReq        = goodsPb.GoodsDetailReq
	GoodsDetailResp       = goodsPb.GoodsDetailResp
	GoodsInfoItem         = goodsPb.GoodsInfoItem
	GoodsItem             = goodsPb.GoodsItem
	GoodsListReq          = goodsPb.GoodsListReq
	GoodsListResp         = goodsPb.GoodsListResp
	OnOffGoodsReq         = goodsPb.OnOffGoodsReq
	OnOffGoodsResp        = goodsPb.OnOffGoodsResp

	Goods interface {
		GetGoodsList(ctx context.Context, in *GoodsListReq, opts ...grpc.CallOption) (*GoodsListResp, error)
		GetGoodsDetail(ctx context.Context, in *GoodsDetailReq, opts ...grpc.CallOption) (*GoodsDetailResp, error)
		AddGoods(ctx context.Context, in *AddGoodsReq, opts ...grpc.CallOption) (*AddGoodsResp, error)
		OnOffGoods(ctx context.Context, in *OnOffGoodsReq, opts ...grpc.CallOption) (*OnOffGoodsResp, error)
		GetAdminGoodsList(ctx context.Context, in *AdminGoodsListReq, opts ...grpc.CallOption) (*AdminGoodsListResp, error)
		BatchGetGoodsInfo(ctx context.Context, in *BatchGetGoodsInfoReq, opts ...grpc.CallOption) (*BatchGetGoodsInfoResp, error)
	}

	defaultGoods struct {
		cli zrpc.Client
	}
)

func NewGoods(cli zrpc.Client) Goods {
	return &defaultGoods{
		cli: cli,
	}
}

func (m *defaultGoods) GetGoodsList(ctx context.Context, in *GoodsListReq, opts ...grpc.CallOption) (*GoodsListResp, error) {
	client := goodsPb.NewGoodsClient(m.cli.Conn())
	return client.GetGoodsList(ctx, in, opts...)
}

func (m *defaultGoods) GetGoodsDetail(ctx context.Context, in *GoodsDetailReq, opts ...grpc.CallOption) (*GoodsDetailResp, error) {
	client := goodsPb.NewGoodsClient(m.cli.Conn())
	return client.GetGoodsDetail(ctx, in, opts...)
}

func (m *defaultGoods) AddGoods(ctx context.Context, in *AddGoodsReq, opts ...grpc.CallOption) (*AddGoodsResp, error) {
	client := goodsPb.NewGoodsClient(m.cli.Conn())
	return client.AddGoods(ctx, in, opts...)
}

func (m *defaultGoods) OnOffGoods(ctx context.Context, in *OnOffGoodsReq, opts ...grpc.CallOption) (*OnOffGoodsResp, error) {
	client := goodsPb.NewGoodsClient(m.cli.Conn())
	return client.OnOffGoods(ctx, in, opts...)
}

func (m *defaultGoods) GetAdminGoodsList(ctx context.Context, in *AdminGoodsListReq, opts ...grpc.CallOption) (*AdminGoodsListResp, error) {
	client := goodsPb.NewGoodsClient(m.cli.Conn())
	return client.GetAdminGoodsList(ctx, in, opts...)
}

func (m *defaultGoods) BatchGetGoodsInfo(ctx context.Context, in *BatchGetGoodsInfoReq, opts ...grpc.CallOption) (*BatchGetGoodsInfoResp, error) {
	client := goodsPb.NewGoodsClient(m.cli.Conn())
	return client.BatchGetGoodsInfo(ctx, in, opts...)
}
