---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by w3110.
--- DateTime: 2026/9/14 12:53
---
local key=KEYS[1]
local num=tonumber(ARGV[1])
local frozen=tonumber(redis.call("HGET",key,"frozen"))
if frozen>=num then
    redis.call("HINCRBY",key,"frozen",0-num)
    redis.call("HINCRBY",key,"available",num)
    return 1
end
return 0