---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by w3110.
--- DateTime: 2026/9/14 23:51
---
local key=KEYS[1]
local num=tonumber(ARGV[1])
local available=tonumber(redis.call("HGET",key,"available"))
if available>=num and available>0 then
    redis.call("HINCRBY",key,"frozen",num)
    redis.call("HINCRBY",key,"available",0-num)
    return 1
end
return 0