syntax = "proto3";

package order;

option go_package = "./orderPb";


// 创建订单请求
message CreateOrderReq {
  repeated string goods_ids = 1;
  string receiver_name = 2;
  string receiver_phone = 3;
  string receiver_address = 4;
  optional string remark = 5;
  string user_id=6;
}

// 创建订单响应
message CreateOrderResp {
  string order_no = 1;
}

// 订单明细VO
message OrderItemVO {
  string goods_id =1;
  string goods_name =2;
  string goods_cover =3;
  string goods_spec =4;     //商品规格
  string goods_price =5;    //下单快照单价
  int64 goods_num =6;       //购买数量
  string subtotal_price =7; //单行商品小计 =单价*数量（优惠前）
}

// 订单预览（确认订单页）请求
message OrderPreviewReq {
  string user_id=2;
  repeated string goods_ids =1;
}

// 订单预览响应
message OrderPreviewResp {
  string receiver_name =1;
  string receiver_phone =2;
  string receiver_address =3;
  string total_amount =4;
  string pay_amount =5;
  repeated PreviewItemVO item_list =6;
}

//预览商品VO
message PreviewItemVO {
  string goods_id =1;
  string goods_name =2;
  string goods_cover =3;
  string goods_price =4;   //单品单价，string存decimal
  string goods_origin_price=7;
  int64 goods_num =5;     //购买数量
  string subtotal_price =6;//该商品小计
}
message OrderOffReq{
  string orderNo=1;
  string userId=2;
}
message OrderOffResp{
  bool ok=1;
}
message OrderPayReq{
  string userId=1;
  string orderNo=2;
}
message OrderPayResp{
  bool ok=1;
}
service order{
  rpc CreateOrder (CreateOrderReq) returns (CreateOrderResp);
  rpc PreviewOrder (OrderPreviewReq) returns (OrderPreviewResp);
  rpc OffOrder (OrderOffReq) returns (OrderOffResp);
  rpc PayOrder (OrderPayReq) returns (OrderPayResp);
}