---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by w3110.
--- DateTime: 2026/8/30 23:21
---
local cartKey=KEYS[1]
local goodsFiled=ARGV[1]
local snapJson=ARGV[2]


local old=redis.call("HGET",cartKey,goodsFiled)

if not old then
    return -1
end
local obj=cjson.decode(old)
local snap=cjson.decode(snapJson)
obj.name=snap.name
obj.cover=snap.cover
obj.price=snap.price
redis.call("HSET",cartKey,goodsFiled,cjson.encode(obj))
return 1