---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by w3110.
--- DateTime: 2026/8/30 23:59
---
local cartKey=KEYS[1]
local goodsField=ARGV[1]
local num=tonumber(ARGV[2])
local selected=tonumber(ARGV[3])

local old=redis.call("HGET",cartKey,goodsField)

if not old then
    return -1
end
local obj=cjson.decode(old)
obj.num=num
obj.selected=selected
redis.call("HSET",cartKey,goodsField,cjson.encode(obj))
return 1