// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/order.proto

package orderPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建订单请求
type CreateOrderReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GoodsIds        []string               `protobuf:"bytes,1,rep,name=goods_ids,json=goodsIds,proto3" json:"goods_ids,omitempty"`
	ReceiverName    string                 `protobuf:"bytes,2,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	ReceiverPhone   string                 `protobuf:"bytes,3,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`
	ReceiverAddress string                 `protobuf:"bytes,4,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"`
	Remark          *string                `protobuf:"bytes,5,opt,name=remark,proto3,oneof" json:"remark,omitempty"`
	UserId          string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderReq) GetGoodsIds() []string {
	if x != nil {
		return x.GoodsIds
	}
	return nil
}

func (x *CreateOrderReq) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *CreateOrderReq) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

func (x *CreateOrderReq) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

func (x *CreateOrderReq) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

func (x *CreateOrderReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 创建订单响应
type CreateOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	PayAmount     string                 `protobuf:"bytes,2,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	TotalAmount   string                 `protobuf:"bytes,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResp) Reset() {
	*x = CreateOrderResp{}
	mi := &file_proto_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResp) ProtoMessage() {}

func (x *CreateOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResp.ProtoReflect.Descriptor instead.
func (*CreateOrderResp) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreateOrderResp) GetPayAmount() string {
	if x != nil {
		return x.PayAmount
	}
	return ""
}

func (x *CreateOrderResp) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

// 订单详情请求 orderNo来自url路径参数
type OrderDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDetailReq) Reset() {
	*x = OrderDetailReq{}
	mi := &file_proto_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetailReq) ProtoMessage() {}

func (x *OrderDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetailReq.ProtoReflect.Descriptor instead.
func (*OrderDetailReq) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderDetailReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

// 订单详情响应
type OrderDetailResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderNo          string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"` //雪花业务订单号
	Status           int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`                 //订单状态码
	ReceiverName     string                 `protobuf:"bytes,3,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	ReceiverPhone    string                 `protobuf:"bytes,4,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`
	ReceiverAddress  string                 `protobuf:"bytes,5,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"`
	Remark           string                 `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"` //用户备注
	TotalGoodsAmount string                 `protobuf:"bytes,7,opt,name=total_goods_amount,json=totalGoodsAmount,proto3" json:"total_goods_amount,omitempty"`
	PayAmount        string                 `protobuf:"bytes,8,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`      //用户实际支付金额
	PayType          int64                  `protobuf:"varint,9,opt,name=pay_type,json=payType,proto3" json:"pay_type,omitempty"`           //0未选择 1微信 2支付宝
	CreateTime       int64                  `protobuf:"varint,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` //创建时间 毫秒时间戳
	PayTime          int64                  `protobuf:"varint,11,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`          //支付成功时间，0未支付
	ExpireTime       int64                  `protobuf:"varint,12,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` //待支付过期时间
	ItemList         []*OrderItemVO         `protobuf:"bytes,13,rep,name=item_list,json=itemList,proto3" json:"item_list,omitempty"`        //订单商品明细
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrderDetailResp) Reset() {
	*x = OrderDetailResp{}
	mi := &file_proto_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetailResp) ProtoMessage() {}

func (x *OrderDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetailResp.ProtoReflect.Descriptor instead.
func (*OrderDetailResp) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{3}
}

func (x *OrderDetailResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderDetailResp) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderDetailResp) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *OrderDetailResp) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

func (x *OrderDetailResp) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

func (x *OrderDetailResp) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *OrderDetailResp) GetTotalGoodsAmount() string {
	if x != nil {
		return x.TotalGoodsAmount
	}
	return ""
}

func (x *OrderDetailResp) GetPayAmount() string {
	if x != nil {
		return x.PayAmount
	}
	return ""
}

func (x *OrderDetailResp) GetPayType() int64 {
	if x != nil {
		return x.PayType
	}
	return 0
}

func (x *OrderDetailResp) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *OrderDetailResp) GetPayTime() int64 {
	if x != nil {
		return x.PayTime
	}
	return 0
}

func (x *OrderDetailResp) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *OrderDetailResp) GetItemList() []*OrderItemVO {
	if x != nil {
		return x.ItemList
	}
	return nil
}

// 订单明细VO
type OrderItemVO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       string                 `protobuf:"bytes,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	GoodsName     string                 `protobuf:"bytes,2,opt,name=goods_name,json=goodsName,proto3" json:"goods_name,omitempty"`
	GoodsCover    string                 `protobuf:"bytes,3,opt,name=goods_cover,json=goodsCover,proto3" json:"goods_cover,omitempty"`
	GoodsSpec     string                 `protobuf:"bytes,4,opt,name=goods_spec,json=goodsSpec,proto3" json:"goods_spec,omitempty"`             //商品规格
	GoodsPrice    string                 `protobuf:"bytes,5,opt,name=goods_price,json=goodsPrice,proto3" json:"goods_price,omitempty"`          //下单快照单价
	GoodsNum      int64                  `protobuf:"varint,6,opt,name=goods_num,json=goodsNum,proto3" json:"goods_num,omitempty"`               //购买数量
	SubtotalPrice string                 `protobuf:"bytes,7,opt,name=subtotal_price,json=subtotalPrice,proto3" json:"subtotal_price,omitempty"` //单行商品小计 =单价*数量（优惠前）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemVO) Reset() {
	*x = OrderItemVO{}
	mi := &file_proto_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemVO) ProtoMessage() {}

func (x *OrderItemVO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemVO.ProtoReflect.Descriptor instead.
func (*OrderItemVO) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderItemVO) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *OrderItemVO) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *OrderItemVO) GetGoodsCover() string {
	if x != nil {
		return x.GoodsCover
	}
	return ""
}

func (x *OrderItemVO) GetGoodsSpec() string {
	if x != nil {
		return x.GoodsSpec
	}
	return ""
}

func (x *OrderItemVO) GetGoodsPrice() string {
	if x != nil {
		return x.GoodsPrice
	}
	return ""
}

func (x *OrderItemVO) GetGoodsNum() int64 {
	if x != nil {
		return x.GoodsNum
	}
	return 0
}

func (x *OrderItemVO) GetSubtotalPrice() string {
	if x != nil {
		return x.SubtotalPrice
	}
	return ""
}

// 订单预览（确认订单页）请求
type OrderPreviewReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GoodsIds      []string               `protobuf:"bytes,1,rep,name=goods_ids,json=goodsIds,proto3" json:"goods_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPreviewReq) Reset() {
	*x = OrderPreviewReq{}
	mi := &file_proto_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPreviewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPreviewReq) ProtoMessage() {}

func (x *OrderPreviewReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPreviewReq.ProtoReflect.Descriptor instead.
func (*OrderPreviewReq) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{5}
}

func (x *OrderPreviewReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderPreviewReq) GetGoodsIds() []string {
	if x != nil {
		return x.GoodsIds
	}
	return nil
}

// 订单预览响应
type OrderPreviewResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReceiverName    string                 `protobuf:"bytes,1,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	ReceiverPhone   string                 `protobuf:"bytes,2,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`
	ReceiverAddress string                 `protobuf:"bytes,3,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"`
	TotalAmount     string                 `protobuf:"bytes,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	PayAmount       string                 `protobuf:"bytes,5,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	ItemList        []*PreviewItemVO       `protobuf:"bytes,6,rep,name=item_list,json=itemList,proto3" json:"item_list,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderPreviewResp) Reset() {
	*x = OrderPreviewResp{}
	mi := &file_proto_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPreviewResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPreviewResp) ProtoMessage() {}

func (x *OrderPreviewResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPreviewResp.ProtoReflect.Descriptor instead.
func (*OrderPreviewResp) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{6}
}

func (x *OrderPreviewResp) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *OrderPreviewResp) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

func (x *OrderPreviewResp) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

func (x *OrderPreviewResp) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *OrderPreviewResp) GetPayAmount() string {
	if x != nil {
		return x.PayAmount
	}
	return ""
}

func (x *OrderPreviewResp) GetItemList() []*PreviewItemVO {
	if x != nil {
		return x.ItemList
	}
	return nil
}

// 预览商品VO
type PreviewItemVO struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GoodsId          string                 `protobuf:"bytes,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	GoodsName        string                 `protobuf:"bytes,2,opt,name=goods_name,json=goodsName,proto3" json:"goods_name,omitempty"`
	GoodsCover       string                 `protobuf:"bytes,3,opt,name=goods_cover,json=goodsCover,proto3" json:"goods_cover,omitempty"`
	GoodsPrice       string                 `protobuf:"bytes,4,opt,name=goods_price,json=goodsPrice,proto3" json:"goods_price,omitempty"` //单品单价，string存decimal
	GoodsOriginPrice string                 `protobuf:"bytes,7,opt,name=goods_origin_price,json=goodsOriginPrice,proto3" json:"goods_origin_price,omitempty"`
	GoodsNum         int64                  `protobuf:"varint,5,opt,name=goods_num,json=goodsNum,proto3" json:"goods_num,omitempty"`               //购买数量
	SubtotalPrice    string                 `protobuf:"bytes,6,opt,name=subtotal_price,json=subtotalPrice,proto3" json:"subtotal_price,omitempty"` //该商品小计
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PreviewItemVO) Reset() {
	*x = PreviewItemVO{}
	mi := &file_proto_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewItemVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewItemVO) ProtoMessage() {}

func (x *PreviewItemVO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewItemVO.ProtoReflect.Descriptor instead.
func (*PreviewItemVO) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{7}
}

func (x *PreviewItemVO) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *PreviewItemVO) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *PreviewItemVO) GetGoodsCover() string {
	if x != nil {
		return x.GoodsCover
	}
	return ""
}

func (x *PreviewItemVO) GetGoodsPrice() string {
	if x != nil {
		return x.GoodsPrice
	}
	return ""
}

func (x *PreviewItemVO) GetGoodsOriginPrice() string {
	if x != nil {
		return x.GoodsOriginPrice
	}
	return ""
}

func (x *PreviewItemVO) GetGoodsNum() int64 {
	if x != nil {
		return x.GoodsNum
	}
	return 0
}

func (x *PreviewItemVO) GetSubtotalPrice() string {
	if x != nil {
		return x.SubtotalPrice
	}
	return ""
}

var File_proto_order_proto protoreflect.FileDescriptor

const file_proto_order_proto_rawDesc = "" +
	"\n" +
	"\x11proto/order.proto\x12\x05order\"\xe5\x01\n" +
	"\x0eCreateOrderReq\x12\x1b\n" +
	"\tgoods_ids\x18\x01 \x03(\tR\bgoodsIds\x12#\n" +
	"\rreceiver_name\x18\x02 \x01(\tR\freceiverName\x12%\n" +
	"\x0ereceiver_phone\x18\x03 \x01(\tR\rreceiverPhone\x12)\n" +
	"\x10receiver_address\x18\x04 \x01(\tR\x0freceiverAddress\x12\x1b\n" +
	"\x06remark\x18\x05 \x01(\tH\x00R\x06remark\x88\x01\x01\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userIdB\t\n" +
	"\a_remark\"n\n" +
	"\x0fCreateOrderResp\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1d\n" +
	"\n" +
	"pay_amount\x18\x02 \x01(\tR\tpayAmount\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\tR\vtotalAmount\"+\n" +
	"\x0eOrderDetailReq\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\"\xc9\x03\n" +
	"\x0fOrderDetailResp\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\x12#\n" +
	"\rreceiver_name\x18\x03 \x01(\tR\freceiverName\x12%\n" +
	"\x0ereceiver_phone\x18\x04 \x01(\tR\rreceiverPhone\x12)\n" +
	"\x10receiver_address\x18\x05 \x01(\tR\x0freceiverAddress\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark\x12,\n" +
	"\x12total_goods_amount\x18\a \x01(\tR\x10totalGoodsAmount\x12\x1d\n" +
	"\n" +
	"pay_amount\x18\b \x01(\tR\tpayAmount\x12\x19\n" +
	"\bpay_type\x18\t \x01(\x03R\apayType\x12\x1f\n" +
	"\vcreate_time\x18\n" +
	" \x01(\x03R\n" +
	"createTime\x12\x19\n" +
	"\bpay_time\x18\v \x01(\x03R\apayTime\x12\x1f\n" +
	"\vexpire_time\x18\f \x01(\x03R\n" +
	"expireTime\x12/\n" +
	"\titem_list\x18\r \x03(\v2\x12.order.OrderItemVOR\bitemList\"\xec\x01\n" +
	"\vOrderItemVO\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\tR\agoodsId\x12\x1d\n" +
	"\n" +
	"goods_name\x18\x02 \x01(\tR\tgoodsName\x12\x1f\n" +
	"\vgoods_cover\x18\x03 \x01(\tR\n" +
	"goodsCover\x12\x1d\n" +
	"\n" +
	"goods_spec\x18\x04 \x01(\tR\tgoodsSpec\x12\x1f\n" +
	"\vgoods_price\x18\x05 \x01(\tR\n" +
	"goodsPrice\x12\x1b\n" +
	"\tgoods_num\x18\x06 \x01(\x03R\bgoodsNum\x12%\n" +
	"\x0esubtotal_price\x18\a \x01(\tR\rsubtotalPrice\"G\n" +
	"\x0fOrderPreviewReq\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tgoods_ids\x18\x01 \x03(\tR\bgoodsIds\"\xfe\x01\n" +
	"\x10OrderPreviewResp\x12#\n" +
	"\rreceiver_name\x18\x01 \x01(\tR\freceiverName\x12%\n" +
	"\x0ereceiver_phone\x18\x02 \x01(\tR\rreceiverPhone\x12)\n" +
	"\x10receiver_address\x18\x03 \x01(\tR\x0freceiverAddress\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\tR\vtotalAmount\x12\x1d\n" +
	"\n" +
	"pay_amount\x18\x05 \x01(\tR\tpayAmount\x121\n" +
	"\titem_list\x18\x06 \x03(\v2\x14.order.PreviewItemVOR\bitemList\"\xfd\x01\n" +
	"\rPreviewItemVO\x12\x19\n" +
	"\bgoods_id\x18\x01 \x01(\tR\agoodsId\x12\x1d\n" +
	"\n" +
	"goods_name\x18\x02 \x01(\tR\tgoodsName\x12\x1f\n" +
	"\vgoods_cover\x18\x03 \x01(\tR\n" +
	"goodsCover\x12\x1f\n" +
	"\vgoods_price\x18\x04 \x01(\tR\n" +
	"goodsPrice\x12,\n" +
	"\x12goods_origin_price\x18\a \x01(\tR\x10goodsOriginPrice\x12\x1b\n" +
	"\tgoods_num\x18\x05 \x01(\x03R\bgoodsNum\x12%\n" +
	"\x0esubtotal_price\x18\x06 \x01(\tR\rsubtotalPrice2\xc7\x01\n" +
	"\x05order\x12<\n" +
	"\vCreateOrder\x12\x15.order.CreateOrderReq\x1a\x16.order.CreateOrderResp\x12?\n" +
	"\x0eGetOrderDetail\x12\x15.order.OrderDetailReq\x1a\x16.order.OrderDetailResp\x12?\n" +
	"\fPreviewOrder\x12\x16.order.OrderPreviewReq\x1a\x17.order.OrderPreviewRespB\vZ\t./orderPbb\x06proto3"

var (
	file_proto_order_proto_rawDescOnce sync.Once
	file_proto_order_proto_rawDescData []byte
)

func file_proto_order_proto_rawDescGZIP() []byte {
	file_proto_order_proto_rawDescOnce.Do(func() {
		file_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_proto_rawDesc), len(file_proto_order_proto_rawDesc)))
	})
	return file_proto_order_proto_rawDescData
}

var file_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_order_proto_goTypes = []any{
	(*CreateOrderReq)(nil),   // 0: order.CreateOrderReq
	(*CreateOrderResp)(nil),  // 1: order.CreateOrderResp
	(*OrderDetailReq)(nil),   // 2: order.OrderDetailReq
	(*OrderDetailResp)(nil),  // 3: order.OrderDetailResp
	(*OrderItemVO)(nil),      // 4: order.OrderItemVO
	(*OrderPreviewReq)(nil),  // 5: order.OrderPreviewReq
	(*OrderPreviewResp)(nil), // 6: order.OrderPreviewResp
	(*PreviewItemVO)(nil),    // 7: order.PreviewItemVO
}
var file_proto_order_proto_depIdxs = []int32{
	4, // 0: order.OrderDetailResp.item_list:type_name -> order.OrderItemVO
	7, // 1: order.OrderPreviewResp.item_list:type_name -> order.PreviewItemVO
	0, // 2: order.order.CreateOrder:input_type -> order.CreateOrderReq
	2, // 3: order.order.GetOrderDetail:input_type -> order.OrderDetailReq
	5, // 4: order.order.PreviewOrder:input_type -> order.OrderPreviewReq
	1, // 5: order.order.CreateOrder:output_type -> order.CreateOrderResp
	3, // 6: order.order.GetOrderDetail:output_type -> order.OrderDetailResp
	6, // 7: order.order.PreviewOrder:output_type -> order.OrderPreviewResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_order_proto_init() }
func file_proto_order_proto_init() {
	if File_proto_order_proto != nil {
		return
	}
	file_proto_order_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_proto_rawDesc), len(file_proto_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_order_proto_goTypes,
		DependencyIndexes: file_proto_order_proto_depIdxs,
		MessageInfos:      file_proto_order_proto_msgTypes,
	}.Build()
	File_proto_order_proto = out.File
	file_proto_order_proto_goTypes = nil
	file_proto_order_proto_depIdxs = nil
}
