// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: order.proto

package server

import (
	"context"

	"zeromall/order/rpc/internal/logic"
	"zeromall/order/rpc/internal/svc"
	"zeromall/order/rpc/orderPb"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	orderPb.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) CreateOrder(ctx context.Context, in *orderPb.CreateOrderReq) (*orderPb.CreateOrderResp, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *OrderServer) GetOrderDetail(ctx context.Context, in *orderPb.OrderDetailReq) (*orderPb.OrderDetailResp, error) {
	l := logic.NewGetOrderDetailLogic(ctx, s.svcCtx)
	return l.GetOrderDetail(in)
}

func (s *OrderServer) PreviewOrder(ctx context.Context, in *orderPb.OrderPreviewReq) (*orderPb.OrderPreviewResp, error) {
	l := logic.NewPreviewOrderLogic(ctx, s.svcCtx)
	return l.PreviewOrder(in)
}
