// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package user

import (
	"context"

	"zeromall/user/rpc/userpb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CaptchaReq       = userpb.CaptchaReq
	CaptchaResp      = userpb.CaptchaResp
	ChangeInfoReq    = userpb.ChangeInfoReq
	ChangeInfoResp   = userpb.ChangeInfoResp
	GetRegionReq     = userpb.GetRegionReq
	GetRegionResp    = userpb.GetRegionResp
	GetSellPowerReq  = userpb.GetSellPowerReq
	GetSellPowerResp = userpb.GetSellPowerResp
	LoginReq         = userpb.LoginReq
	LoginResp        = userpb.LoginResp
	RegionItem       = userpb.RegionItem
	RegisterReq      = userpb.RegisterReq
	RegisterResp     = userpb.RegisterResp
	UserInfoReq      = userpb.UserInfoReq
	UserInfoResp     = userpb.UserInfoResp

	User interface {
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		Captcha(ctx context.Context, in *CaptchaReq, opts ...grpc.CallOption) (*CaptchaResp, error)
		UserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoResp, error)
		ChangeInfo(ctx context.Context, in *ChangeInfoReq, opts ...grpc.CallOption) (*ChangeInfoResp, error)
		GetRegion(ctx context.Context, in *GetRegionReq, opts ...grpc.CallOption) (*GetRegionResp, error)
		GetSellPower(ctx context.Context, in *GetSellPowerReq, opts ...grpc.CallOption) (*GetSellPowerResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := userpb.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUser) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := userpb.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) Captcha(ctx context.Context, in *CaptchaReq, opts ...grpc.CallOption) (*CaptchaResp, error) {
	client := userpb.NewUserClient(m.cli.Conn())
	return client.Captcha(ctx, in, opts...)
}

func (m *defaultUser) UserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoResp, error) {
	client := userpb.NewUserClient(m.cli.Conn())
	return client.UserInfo(ctx, in, opts...)
}

func (m *defaultUser) ChangeInfo(ctx context.Context, in *ChangeInfoReq, opts ...grpc.CallOption) (*ChangeInfoResp, error) {
	client := userpb.NewUserClient(m.cli.Conn())
	return client.ChangeInfo(ctx, in, opts...)
}

func (m *defaultUser) GetRegion(ctx context.Context, in *GetRegionReq, opts ...grpc.CallOption) (*GetRegionResp, error) {
	client := userpb.NewUserClient(m.cli.Conn())
	return client.GetRegion(ctx, in, opts...)
}

func (m *defaultUser) GetSellPower(ctx context.Context, in *GetSellPowerReq, opts ...grpc.CallOption) (*GetSellPowerResp, error) {
	client := userpb.NewUserClient(m.cli.Conn())
	return client.GetSellPower(ctx, in, opts...)
}
