// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	goodsFieldNames          = builder.RawFieldNames(&Goods{})
	goodsRows                = strings.Join(goodsFieldNames, ",")
	goodsRowsExpectAutoSet   = strings.Join(stringx.Remove(goodsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	goodsRowsWithPlaceHolder = strings.Join(stringx.Remove(goodsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	goodsModel interface {
		Insert(ctx context.Context, data *Goods) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Goods, error)
		FindOneByGoodsId(ctx context.Context, goodsId string) (*Goods, error)
		Update(ctx context.Context, data *Goods) error
		Delete(ctx context.Context, id int64) error
		PageBreakFind(ctx context.Context, categoryId int64, page int32, pageSize int32) ([]*Goods, error)
		FindByOwnId(ctx context.Context, userId string) ([]*Goods, error)
		UpdateFields(ctx context.Context, goodsId string, setMap map[string]any) (int64, error)
	}

	defaultGoodsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Goods struct {
		Id                int64          `db:"id"`                  // 数据库自增主键
		GoodsId           string         `db:"goods_id"`            // 商品业务唯一ID（uuid，对外暴露）
		Name              string         `db:"name"`                // 商品名称
		Cover             string         `db:"cover"`               // 商品封面图
		PriceCent         int64          `db:"price_cent"`          // 售价(分)
		OriginalPriceCent int64          `db:"original_price_cent"` // 原价(分)
		Stock             int64          `db:"stock"`               // 库存
		Sales             int64          `db:"sales"`               // 销量
		CategoryId        int64          `db:"category_id"`         // 分类id
		Desc              string         `db:"desc"`                // 商品详情
		Status            int64          `db:"status"`              // 状态 1上架 2下架 3删除标记
		CreatedAt         time.Time      `db:"created_at"`
		UpdatedAt         time.Time      `db:"updated_at"`
		DeletedAt         sql.NullTime   `db:"deleted_at"` // 软删除时间，null=未删除
		OwnUserId         sql.NullString `db:"own_userId"` // 售卖者
	}
)

func newGoodsModel(conn sqlx.SqlConn) *defaultGoodsModel {
	return &defaultGoodsModel{
		conn:  conn,
		table: "`goods`",
	}
}

func (m *defaultGoodsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGoodsModel) FindOne(ctx context.Context, id int64) (*Goods, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", goodsRows, m.table)
	var resp Goods
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGoodsModel) FindOneByGoodsId(ctx context.Context, goodsId string) (*Goods, error) {
	var resp Goods
	query := fmt.Sprintf("select %s from %s where `goods_id` = ? limit 1", goodsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, goodsId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGoodsModel) Insert(ctx context.Context, data *Goods) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, goodsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.GoodsId, data.Name, data.Cover, data.PriceCent, data.OriginalPriceCent, data.Stock, data.Sales, data.CategoryId, data.Desc, data.Status, data.DeletedAt, data.OwnUserId)
	return ret, err
}

func (m *defaultGoodsModel) Update(ctx context.Context, newData *Goods) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, goodsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.GoodsId, newData.Name, newData.Cover, newData.PriceCent, newData.OriginalPriceCent, newData.Stock, newData.Sales, newData.CategoryId, newData.Desc, newData.Status, newData.DeletedAt, newData.OwnUserId, newData.Id)
	return err
}

func (m *defaultGoodsModel) tableName() string {
	return m.table
}
