// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	areaFieldNames          = builder.RawFieldNames(&Area{})
	areaRows                = strings.Join(areaFieldNames, ",")
	areaRowsExpectAutoSet   = strings.Join(stringx.Remove(areaFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	areaRowsWithPlaceHolder = strings.Join(stringx.Remove(areaFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	areaModel interface {
		Insert(ctx context.Context, data *Area) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Area, error)
		Update(ctx context.Context, data *Area) error
		Delete(ctx context.Context, id int64) error
		SelectFields(ctx context.Context, level int64, pId int64) ([]*Area, error)
		AreaLevel3IsExist(ctx context.Context, addressId int64) (bool, error)
	}

	defaultAreaModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Area struct {
		Id        int64          `db:"id"`        // ID
		Pid       int64          `db:"pid"`       // 父id
		Shortname sql.NullString `db:"shortname"` // 简称
		Name      sql.NullString `db:"name"`      // 名称
		Mergename sql.NullString `db:"mergename"` // 全称
		Level     int64          `db:"level"`     // 层级 0 1 2 省市区县
	}
)

func newAreaModel(conn sqlx.SqlConn) *defaultAreaModel {
	return &defaultAreaModel{
		conn:  conn,
		table: "`area`",
	}
}

func (m *defaultAreaModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAreaModel) FindOne(ctx context.Context, id int64) (*Area, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", areaRows, m.table)
	var resp Area
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAreaModel) Insert(ctx context.Context, data *Area) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, areaRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Pid, data.Shortname, data.Name, data.Mergename, data.Level)
	return ret, err
}

func (m *defaultAreaModel) Update(ctx context.Context, data *Area) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, areaRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Pid, data.Shortname, data.Name, data.Mergename, data.Level, data.Id)
	return err
}

func (m *defaultAreaModel) tableName() string {
	return m.table
}
