// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userReceiveAddressFieldNames          = builder.RawFieldNames(&UserReceiveAddress{})
	userReceiveAddressRows                = strings.Join(userReceiveAddressFieldNames, ",")
	userReceiveAddressRowsExpectAutoSet   = strings.Join(stringx.Remove(userReceiveAddressFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userReceiveAddressRowsWithPlaceHolder = strings.Join(stringx.Remove(userReceiveAddressFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userReceiveAddressModel interface {
		Insert(ctx context.Context, data *UserReceiveAddress) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserReceiveAddress, error)
		Update(ctx context.Context, data *UserReceiveAddress) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserReceiveAddressModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserReceiveAddress struct {
		Id            int64     `db:"id"`             // 主键ID
		UserId        int64     `db:"user_id"`        // 用户ID
		ReceiverName  string    `db:"receiver_name"`  // 收件人姓名
		ReceiverPhone string    `db:"receiver_phone"` // 收件人手机号
		AddressId     int64     `db:"address_id"`     // 地区areaId
		Detail        string    `db:"detail"`         // 详细街道地址
		IsDefault     int64     `db:"is_default"`     // 是否默认地址 0否 1是
		CreateTime    time.Time `db:"create_time"`    // 创建时间
		UpdateTime    time.Time `db:"update_time"`    // 更新时间
		Deleted       int64     `db:"deleted"`        // 逻辑删除 0未删除 1已删除
	}
)

func newUserReceiveAddressModel(conn sqlx.SqlConn) *defaultUserReceiveAddressModel {
	return &defaultUserReceiveAddressModel{
		conn:  conn,
		table: "`user_receive_address`",
	}
}

func (m *defaultUserReceiveAddressModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserReceiveAddressModel) FindOne(ctx context.Context, id int64) (*UserReceiveAddress, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userReceiveAddressRows, m.table)
	var resp UserReceiveAddress
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserReceiveAddressModel) Insert(ctx context.Context, data *UserReceiveAddress) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, userReceiveAddressRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ReceiverName, data.ReceiverPhone, data.AddressId, data.Detail, data.IsDefault, data.Deleted)
	return ret, err
}

func (m *defaultUserReceiveAddressModel) Update(ctx context.Context, data *UserReceiveAddress) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userReceiveAddressRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ReceiverName, data.ReceiverPhone, data.AddressId, data.Detail, data.IsDefault, data.Deleted, data.Id)
	return err
}

func (m *defaultUserReceiveAddressModel) tableName() string {
	return m.table
}
