// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: balance.proto

package balance

import (
	"context"

	"zeromall/balance/rpc/balancePb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeductBalanceReq  = balancePb.DeductBalanceReq
	DeductBalanceResp = balancePb.DeductBalanceResp
	RefundBalanceReq  = balancePb.RefundBalanceReq
	RefundBalanceResp = balancePb.RefundBalanceResp

	Balance interface {
		DeductBalance(ctx context.Context, in *DeductBalanceReq, opts ...grpc.CallOption) (*DeductBalanceResp, error)
		RefundBalance(ctx context.Context, in *RefundBalanceReq, opts ...grpc.CallOption) (*RefundBalanceResp, error)
	}

	defaultBalance struct {
		cli zrpc.Client
	}
)

func NewBalance(cli zrpc.Client) Balance {
	return &defaultBalance{
		cli: cli,
	}
}

func (m *defaultBalance) DeductBalance(ctx context.Context, in *DeductBalanceReq, opts ...grpc.CallOption) (*DeductBalanceResp, error) {
	client := balancePb.NewBalanceClient(m.cli.Conn())
	return client.DeductBalance(ctx, in, opts...)
}

func (m *defaultBalance) RefundBalance(ctx context.Context, in *RefundBalanceReq, opts ...grpc.CallOption) (*RefundBalanceResp, error) {
	client := balancePb.NewBalanceClient(m.cli.Conn())
	return client.RefundBalance(ctx, in, opts...)
}
