// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AddReceiveAddressReq struct {
	ReceiveName  string `json:"receiveName"`
	ReceivePhone string `json:"receivePhone"`
	AddressId    int64  `json:"addressId"`
	Detail       string `json:"detail"`
	IsDefault    int64  `json:"isDefault"`
}

type AddressItem struct {
	ReceiveName      string `json:"receiveName"`
	ReceivePhone     string `json:"receivePhone"`
	AddressMergeName string `json:"addressMergeName"`
	IsDefault        int64  `json:"isDefault"`
	Detail           string `json:"detail"`
}

type CaptchaReq struct {
	Phone string `form:"phone"`
}

type CaptchaResp struct {
	Captcha string `json:"captcha"`
}

type ChangeInfoReq struct {
	UserName *string `json:"username,optional,omitempty"`
	Avatar   *string `json:"avatar,optional,omitempty"`
	Age      *uint64 `json:"age,optional,omitempty"`
	Sex      *uint64 `json:"sex,optional,omitempty"`
	Region   *int64  `json:"region,optional,omitempty"`
}

type GetReceiveAddressResp struct {
	List []*AddressItem `json:"list"`
}

type GetRegionReq struct {
	Level *int64 `form:"level,omitempty"`
	PId   *int64 `form:"pId,omitempty"`
}

type GetRegionResp struct {
	List []*RegionItem `json:"list"`
}

type LoginReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type OthersBaseInfoReq struct {
	UserId string `path:"userId"`
}

type OthersBaseInfoResp struct {
	UserName string `json:"username"`
	UserId   string `json:"userId"`
	Avatar   string `json:"avatar"`
	Age      uint64 `json:"age"`
	Sex      uint64 `json:"sex"`
}

type RegionItem struct {
	Id    int64  `json:"id"`
	PId   int64  `json:"pId"`
	Name  string `json:"name"`
	Level int64  `json:"level"`
}

type RegisterReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
	Captcha  string `json:"captcha"`
}

type UserInfoResp struct {
	UserName string `json:"username"`
	UserId   string `json:"userId"`
	Avatar   string `json:"avatar"`
	Phone    string `json:"phone"`
	Age      uint64 `json:"age"`
	Sex      uint64 `json:"sex"`
	Balance  string `json:"balance"`
}
