// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateOrderReq struct {
	GoodsIds        []string `json:"goodsIds"`
	ReceiverName    string   `json:"receiverName"`
	ReceiverPhone   string   `json:"receiverPhone"`
	ReceiverAddress string   `json:"receiverAddress"`
	Remark          *string  `json:"remark"`
}

type CreateOrderResp struct {
	OrderNo     string `json:"orderNo"`
	PayAmount   string `json:"payAmount"`
	TotalAmount string `json:"totalAmount"`
}

type OrderDetailReq struct {
	OrderNo string `path:"orderNo"`
}

type OrderDetailResp struct {
	OrderNo          string         `json:"orderNo"` //雪花业务订单号
	Status           int64          `json:"status"`  //订单状态码
	ReceiverName     string         `json:"receiverName"`
	ReceiverPhone    string         `json:"receiverPhone"`
	ReceiverAddress  string         `json:"receiverAddress"`
	Remark           string         `json:"remark"` //用户备注
	TotalGoodsAmount string         `json:"totalGoodsAmount"`
	PayAmount        string         `json:"payAmount"`  //用户实际支付金额
	PayType          int64          `json:"payType"`    //0未选择 1微信 2支付宝
	CreateTime       int64          `json:"createTime"` //创建时间 毫秒时间戳
	PayTime          int64          `json:"payTime"`    //支付成功时间，0未支付
	ExpireTime       int64          `json:"expireTime"` //待支付过期时间
	ItemList         []*OrderItemVO `json:"itemList"`   //订单商品明细
}

type OrderItemVO struct {
	GoodsId       string `json:"goodsId"`
	GoodsName     string `json:"goodsName"`
	GoodsCover    string `json:"goodsCover"`
	GoodsSpec     string `json:"goodsSpec"`     //商品规格
	GoodsPrice    string `json:"goodsPrice"`    //下单快照单价
	GoodsNum      int64  `json:"goodsNum"`      //购买数量
	SubtotalPrice string `json:"subtotalPrice"` //单行商品小计 =单价*数量（优惠前）
}

type OrderPreviewReq struct {
	GoodsIds []string `json:"goodsIds"`
}

type OrderPreviewResp struct {
	ReceiverName    string           `json:"receiverName"`
	ReceiverPhone   string           `json:"receiverPhone"`
	ReceiverAddress string           `json:"receiverAddress"`
	TotalAmount     string           `json:"totalAmount"`
	PayAmount       string           `json:"payAmount"`
	ItemList        []*PreviewItemVO `json:"itemList"`
}

type PreviewItemVO struct {
	GoodsId       string `json:"goodsId"`
	GoodsName     string `json:"goodsName"`
	GoodsCover    string `json:"goodsCover"`
	GoodsPrice    string `json:"goodsPrice"`    //单品单价，string存decimal
	GoodsNum      int64  `json:"goodsNum"`      //购买数量
	SubtotalPrice string `json:"subtotalPrice"` //该商品小计
}
