// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateOrderReq struct {
	GoodsIds        []string `json:"goodsIds"`
	ReceiverName    string   `json:"receiverName"`
	ReceiverPhone   string   `json:"receiverPhone"`
	ReceiverAddress string   `json:"receiverAddress"`
	Remark          *string  `json:"remark"`
}

type CreateOrderResp struct {
	OrderNo string `json:"orderNo"`
}

type EmptyResp struct {
}

type OrderItemVO struct {
	GoodsId       string `json:"goodsId"`
	GoodsName     string `json:"goodsName"`
	GoodsCover    string `json:"goodsCover"`
	GoodsSpec     string `json:"goodsSpec"`     //商品规格
	GoodsPrice    string `json:"goodsPrice"`    //下单快照单价
	GoodsNum      int64  `json:"goodsNum"`      //购买数量
	SubtotalPrice string `json:"subtotalPrice"` //单行商品小计 =单价*数量（优惠前）
}

type OrderOffReq struct {
	OrderNo string `json:"orderNo"`
}

type OrderPreviewReq struct {
	GoodsIds []string `json:"goodsIds"`
}

type OrderPreviewResp struct {
	ReceiverName    string           `json:"receiverName"`
	ReceiverPhone   string           `json:"receiverPhone"`
	ReceiverAddress string           `json:"receiverAddress"`
	TotalAmount     string           `json:"totalAmount"`
	PayAmount       string           `json:"payAmount"`
	ItemList        []*PreviewItemVO `json:"itemList"`
}

type PayOrderReq struct {
	OrderNo string `json:"orderNo"`
}

type PreviewItemVO struct {
	GoodsId       string `json:"goodsId"`
	GoodsName     string `json:"goodsName"`
	GoodsCover    string `json:"goodsCover"`
	GoodsPrice    string `json:"goodsPrice"`    //单品单价，string存decimal
	GoodsNum      int64  `json:"goodsNum"`      //购买数量
	SubtotalPrice string `json:"subtotalPrice"` //该商品小计
}
