// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	orderLogisticsFieldNames          = builder.RawFieldNames(&OrderLogistics{})
	orderLogisticsRows                = strings.Join(orderLogisticsFieldNames, ",")
	orderLogisticsRowsExpectAutoSet   = strings.Join(stringx.Remove(orderLogisticsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	orderLogisticsRowsWithPlaceHolder = strings.Join(stringx.Remove(orderLogisticsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	orderLogisticsModel interface {
		Insert(ctx context.Context, data *OrderLogistics) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*OrderLogistics, error)
		Update(ctx context.Context, data *OrderLogistics) error
		Delete(ctx context.Context, id int64) error
	}

	defaultOrderLogisticsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	OrderLogistics struct {
		Id              int64          `db:"id"`               // 物流表自身主键
		OrderNo         string         `db:"order_no"`         // 关联订单业务号
		ReceiverName    string         `db:"receiver_name"`    // 收件人姓名快照
		ReceiverPhone   string         `db:"receiver_phone"`   // 收件手机号快照
		ReceiverAddress string         `db:"receiver_address"` // 完整收货地址快照
		LogisticsName   sql.NullString `db:"logistics_name"`   // 快递公司名称
		TrackingNo      sql.NullString `db:"tracking_no"`      // 快递运单号
		CreatedAt       time.Time      `db:"created_at"`
		UpdatedAt       time.Time      `db:"updated_at"`
	}
)

func newOrderLogisticsModel(conn sqlx.SqlConn) *defaultOrderLogisticsModel {
	return &defaultOrderLogisticsModel{
		conn:  conn,
		table: "`order_logistics`",
	}
}

func (m *defaultOrderLogisticsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultOrderLogisticsModel) FindOne(ctx context.Context, id int64) (*OrderLogistics, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", orderLogisticsRows, m.table)
	var resp OrderLogistics
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderLogisticsModel) Insert(ctx context.Context, data *OrderLogistics) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, orderLogisticsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OrderNo, data.ReceiverName, data.ReceiverPhone, data.ReceiverAddress, data.LogisticsName, data.TrackingNo)
	return ret, err
}

func (m *defaultOrderLogisticsModel) Update(ctx context.Context, data *OrderLogistics) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, orderLogisticsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.OrderNo, data.ReceiverName, data.ReceiverPhone, data.ReceiverAddress, data.LogisticsName, data.TrackingNo, data.Id)
	return err
}

func (m *defaultOrderLogisticsModel) tableName() string {
	return m.table
}
