// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	orderItemFieldNames          = builder.RawFieldNames(&OrderItem{})
	orderItemRows                = strings.Join(orderItemFieldNames, ",")
	orderItemRowsExpectAutoSet   = strings.Join(stringx.Remove(orderItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	orderItemRowsWithPlaceHolder = strings.Join(stringx.Remove(orderItemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	orderItemModel interface {
		Insert(ctx context.Context, data *OrderItem) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*OrderItem, error)
		Update(ctx context.Context, data *OrderItem) error
		Delete(ctx context.Context, id int64) error
	}

	defaultOrderItemModel struct {
		conn  sqlx.SqlConn
		table string
	}

	OrderItem struct {
		Id         int64     `db:"id"`          // 明细表自身主键
		OrderNo    string    `db:"order_no"`    // 关联订单业务号
		GoodsId    int64     `db:"goods_id"`    // 商品ID（来自goods服务）
		GoodsName  string    `db:"goods_name"`  // 下单时商品名称快照
		GoodsCover string    `db:"goods_cover"` // 下单时商品封面快照
		PriceCent  int64     `db:"price_cent"`  // 下单时单件价格(分)
		Num        int64     `db:"num"`         // 购买数量
		TotalCent  int64     `db:"total_cent"`  // 本条商品小计金额(分)
		CreatedAt  time.Time `db:"created_at"`
		UpdatedAt  time.Time `db:"updated_at"`
	}
)

func newOrderItemModel(conn sqlx.SqlConn) *defaultOrderItemModel {
	return &defaultOrderItemModel{
		conn:  conn,
		table: "`order_item`",
	}
}

func (m *defaultOrderItemModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultOrderItemModel) FindOne(ctx context.Context, id int64) (*OrderItem, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", orderItemRows, m.table)
	var resp OrderItem
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderItemModel) Insert(ctx context.Context, data *OrderItem) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, orderItemRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OrderNo, data.GoodsId, data.GoodsName, data.GoodsCover, data.PriceCent, data.Num, data.TotalCent)
	return ret, err
}

func (m *defaultOrderItemModel) Update(ctx context.Context, data *OrderItem) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, orderItemRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.OrderNo, data.GoodsId, data.GoodsName, data.GoodsCover, data.PriceCent, data.Num, data.TotalCent, data.Id)
	return err
}

func (m *defaultOrderItemModel) tableName() string {
	return m.table
}
