// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	orderFieldNames          = builder.RawFieldNames(&Order{})
	orderRows                = strings.Join(orderFieldNames, ",")
	orderRowsExpectAutoSet   = strings.Join(stringx.Remove(orderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	orderRowsWithPlaceHolder = strings.Join(stringx.Remove(orderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	orderModel interface {
		Insert(ctx context.Context, data *Order) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Order, error)
		FindOneByOrderNo(ctx context.Context, orderNo int64) (*Order, error)
		Update(ctx context.Context, data *Order) error
		Delete(ctx context.Context, id int64) error
		TxInsert(ctx context.Context, orderData *Order, orderItemData []*OrderItem) (int64, error)
		CloseConditional(ctx context.Context, orderNo string) (int64, error)
	}

	defaultOrderModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Order struct {
		Id          int64          `db:"id"`           // 自增主键id
		OrderNo     int64          `db:"order_no"`     // 雪花id
		UserId      string         `db:"user_id"`      // 下单用户ID（来自user服务）
		TotalCent   int64          `db:"total_cent"`   // 订单原价
		PayCent     int64          `db:"pay_cent"`     // 实付金额(分，优惠后)
		Status      int64          `db:"status"`       // 0待支付 1已支付 2已发货 3已完成 4已取消 5已退款
		PayType     sql.NullInt64  `db:"pay_type"`     // 支付方式 1余额 2微信 3支付宝
		PayTime     sql.NullTime   `db:"pay_time"`     // 支付时间
		DeliverTime sql.NullTime   `db:"deliver_time"` // 发货时间
		ReceiveTime sql.NullTime   `db:"receive_time"` // 确认收货时间
		CancelTime  sql.NullTime   `db:"cancel_time"`  // 订单取消时间
		Remark      sql.NullString `db:"remark"`       // 用户下单备注
		ExpireTime  time.Time      `db:"expire_time"`  // 订单超时关闭时间，一般30分钟
		DeletedAt   sql.NullTime   `db:"deleted_at"`   // 软删除
		CreatedAt   time.Time      `db:"created_at"`
		UpdatedAt   time.Time      `db:"updated_at"`
	}
)

func newOrderModel(conn sqlx.SqlConn) *defaultOrderModel {
	return &defaultOrderModel{
		conn:  conn,
		table: "`order`",
	}
}

func (m *defaultOrderModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultOrderModel) FindOne(ctx context.Context, id int64) (*Order, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", orderRows, m.table)
	var resp Order
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderModel) FindOneByOrderNo(ctx context.Context, orderNo int64) (*Order, error) {
	var resp Order
	query := fmt.Sprintf("select %s from %s where `order_no` = ? limit 1", orderRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, orderNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderModel) Insert(ctx context.Context, data *Order) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, orderRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OrderNo, data.UserId, data.TotalCent, data.PayCent, data.Status, data.PayType, data.PayTime, data.DeliverTime, data.ReceiveTime, data.CancelTime, data.Remark, data.ExpireTime, data.DeletedAt)
	return ret, err
}

func (m *defaultOrderModel) Update(ctx context.Context, newData *Order) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, orderRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.OrderNo, newData.UserId, newData.TotalCent, newData.PayCent, newData.Status, newData.PayType, newData.PayTime, newData.DeliverTime, newData.ReceiveTime, newData.CancelTime, newData.Remark, newData.ExpireTime, newData.DeletedAt, newData.Id)
	return err
}

func (m *defaultOrderModel) tableName() string {
	return m.table
}
