// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	ordersFieldNames          = builder.RawFieldNames(&Orders{})
	ordersRows                = strings.Join(ordersFieldNames, ",")
	ordersRowsExpectAutoSet   = strings.Join(stringx.Remove(ordersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	ordersRowsWithPlaceHolder = strings.Join(stringx.Remove(ordersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	ordersModel interface {
		Insert(ctx context.Context, data *Orders) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Orders, error)
		FindOneByOrderNo(ctx context.Context, orderNo int64) (*Orders, error)
		Update(ctx context.Context, data *Orders) error
		Delete(ctx context.Context, id int64) error
		TxInsert(ctx context.Context, orderData *Orders, orderItemData []*OrderItem, txLogData *TransactionLog) (int64, error)
		CloseConditional(ctx context.Context, orderNo int64) (int64, error)
	}

	defaultOrdersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Orders struct {
		Id          int64          `db:"id"`           // 自增主键id
		OrderNo     int64          `db:"order_no"`     // 雪花id
		UserId      string         `db:"user_id"`      // 下单用户ID（来自user服务）
		TotalCent   int64          `db:"total_cent"`   // 订单原价
		PayCent     int64          `db:"pay_cent"`     // 实付金额(分，优惠后)
		Status      int64          `db:"status"`       // 0待支付 1已支付 2已发货 3已完成 4已取消 5已退款
		PayType     sql.NullInt64  `db:"pay_type"`     // 支付方式 1余额 2微信 3支付宝
		PayTime     sql.NullTime   `db:"pay_time"`     // 支付时间
		DeliverTime sql.NullTime   `db:"deliver_time"` // 发货时间
		ReceiveTime sql.NullTime   `db:"receive_time"` // 确认收货时间
		CancelTime  sql.NullTime   `db:"cancel_time"`  // 订单取消时间
		Remark      sql.NullString `db:"remark"`       // 用户下单备注
		ExpireTime  time.Time      `db:"expire_time"`  // 订单超时关闭时间，一般30分钟
		DeletedAt   sql.NullTime   `db:"deleted_at"`   // 软删除
		CreatedAt   time.Time      `db:"created_at"`
		UpdatedAt   time.Time      `db:"updated_at"`
	}
)

func newOrdersModel(conn sqlx.SqlConn) *defaultOrdersModel {
	return &defaultOrdersModel{
		conn:  conn,
		table: "`orders`",
	}
}

func (m *defaultOrdersModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultOrdersModel) FindOne(ctx context.Context, id int64) (*Orders, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", ordersRows, m.table)
	var resp Orders
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrdersModel) FindOneByOrderNo(ctx context.Context, orderNo int64) (*Orders, error) {
	var resp Orders
	query := fmt.Sprintf("select %s from %s where `order_no` = ? limit 1", ordersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, orderNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrdersModel) Insert(ctx context.Context, data *Orders) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, ordersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OrderNo, data.UserId, data.TotalCent, data.PayCent, data.Status, data.PayType, data.PayTime, data.DeliverTime, data.ReceiveTime, data.CancelTime, data.Remark, data.ExpireTime, data.DeletedAt)
	return ret, err
}

func (m *defaultOrdersModel) Update(ctx context.Context, newData *Orders) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, ordersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.OrderNo, newData.UserId, newData.TotalCent, newData.PayCent, newData.Status, newData.PayType, newData.PayTime, newData.DeliverTime, newData.ReceiveTime, newData.CancelTime, newData.Remark, newData.ExpireTime, newData.DeletedAt, newData.Id)
	return err
}

func (m *defaultOrdersModel) tableName() string {
	return m.table
}
