// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	transactionLogFieldNames          = builder.RawFieldNames(&TransactionLog{})
	transactionLogRows                = strings.Join(transactionLogFieldNames, ",")
	transactionLogRowsExpectAutoSet   = strings.Join(stringx.Remove(transactionLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	transactionLogRowsWithPlaceHolder = strings.Join(stringx.Remove(transactionLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	transactionLogModel interface {
		Insert(ctx context.Context, data *TransactionLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TransactionLog, error)
		FindOneByTxId(ctx context.Context, txId string) (*TransactionLog, error)
		Update(ctx context.Context, data *TransactionLog) error
		Delete(ctx context.Context, id int64) error
		FindStatusByOrderNo(orderNo int64) (*TransactionLog, error)
		UpdateStatusByOrderNo(orderNo int64) error
	}

	defaultTransactionLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TransactionLog struct {
		Id        int64     `db:"id"`
		TxId      string    `db:"tx_id"` // RocketMQ事务消息的unique txId
		OrderNo   int64     `db:"order_no"`
		Status    int64     `db:"status"` // 0:处理中,1:已提交,2:已回滚
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newTransactionLogModel(conn sqlx.SqlConn) *defaultTransactionLogModel {
	return &defaultTransactionLogModel{
		conn:  conn,
		table: "`transaction_log`",
	}
}

func (m *defaultTransactionLogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTransactionLogModel) FindOne(ctx context.Context, id int64) (*TransactionLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", transactionLogRows, m.table)
	var resp TransactionLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTransactionLogModel) FindOneByTxId(ctx context.Context, txId string) (*TransactionLog, error) {
	var resp TransactionLog
	query := fmt.Sprintf("select %s from %s where `tx_id` = ? limit 1", transactionLogRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, txId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTransactionLogModel) Insert(ctx context.Context, data *TransactionLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, transactionLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TxId, data.OrderNo, data.Status)
	return ret, err
}

func (m *defaultTransactionLogModel) Update(ctx context.Context, newData *TransactionLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, transactionLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.TxId, newData.OrderNo, newData.Status, newData.Id)
	return err
}

func (m *defaultTransactionLogModel) tableName() string {
	return m.table
}
