// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AddCartReq struct {
	GoodsId string `json:"goodsId"`
	AddNum  int64  `json:"addNum"`
}

type BatchDeleteReq struct {
	GoodsIds []string `json:"goodsIds"`
}

type CartItem struct {
	Num      int64  `json:"num"`
	Selected int64  `json:"selected"`
	GoodsId  string `json:"goodsId"`
	Name     string `json:"name"`
	Cover    string `json:"cover"`
	Price    string `json:"price"`
}

type CartListResp struct {
	CartList []*CartItem `json:"cartList"`
}

type UpdateCartReq struct {
	GoodsId  string `json:"goodsId"`
	Num      int64  `json:"num"`
	Selected int64  `json:"selected"`
}

type UpdateCartResp struct {
	GoodsId  string `json:"goodsId"`
	Num      int64  `json:"num"`
	Selected int64  `json:"selected"`
}
