---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by w3110.
--- DateTime: 2026/9/15 00:54
---

local key=KEYS[1]
local available=ARGV[1]
local frozen=ARGV[2]

redis.call("HSET",key,"available",available,"frozen",frozen)
return 1