// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: order.proto

package order

import (
	"context"

	"zeromall/order/rpc/orderPb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateOrderReq   = orderPb.CreateOrderReq
	CreateOrderResp  = orderPb.CreateOrderResp
	OrderDetailReq   = orderPb.OrderDetailReq
	OrderDetailResp  = orderPb.OrderDetailResp
	OrderItemVO      = orderPb.OrderItemVO
	OrderPreviewReq  = orderPb.OrderPreviewReq
	OrderPreviewResp = orderPb.OrderPreviewResp
	PreviewItemVO    = orderPb.PreviewItemVO

	Order interface {
		CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
		GetOrderDetail(ctx context.Context, in *OrderDetailReq, opts ...grpc.CallOption) (*OrderDetailResp, error)
		PreviewOrder(ctx context.Context, in *OrderPreviewReq, opts ...grpc.CallOption) (*OrderPreviewResp, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

func (m *defaultOrder) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	client := orderPb.NewOrderClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultOrder) GetOrderDetail(ctx context.Context, in *OrderDetailReq, opts ...grpc.CallOption) (*OrderDetailResp, error) {
	client := orderPb.NewOrderClient(m.cli.Conn())
	return client.GetOrderDetail(ctx, in, opts...)
}

func (m *defaultOrder) PreviewOrder(ctx context.Context, in *OrderPreviewReq, opts ...grpc.CallOption) (*OrderPreviewResp, error) {
	client := orderPb.NewOrderClient(m.cli.Conn())
	return client.PreviewOrder(ctx, in, opts...)
}
