// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/goods.proto

package goodsPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddGoodsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cover         string                 `protobuf:"bytes,2,opt,name=cover,proto3" json:"cover,omitempty"`
	OriginalPrice string                 `protobuf:"bytes,3,opt,name=originalPrice,proto3" json:"originalPrice,omitempty"`
	Price         string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int64                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	CategoryId    int64                  `protobuf:"varint,6,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Desc          string                 `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
	OwnUserId     string                 `protobuf:"bytes,8,opt,name=ownUserId,proto3" json:"ownUserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGoodsReq) Reset() {
	*x = AddGoodsReq{}
	mi := &file_proto_goods_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodsReq) ProtoMessage() {}

func (x *AddGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goods_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodsReq.ProtoReflect.Descriptor instead.
func (*AddGoodsReq) Descriptor() ([]byte, []int) {
	return file_proto_goods_proto_rawDescGZIP(), []int{0}
}

func (x *AddGoodsReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddGoodsReq) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *AddGoodsReq) GetOriginalPrice() string {
	if x != nil {
		return x.OriginalPrice
	}
	return ""
}

func (x *AddGoodsReq) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *AddGoodsReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *AddGoodsReq) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *AddGoodsReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *AddGoodsReq) GetOwnUserId() string {
	if x != nil {
		return x.OwnUserId
	}
	return ""
}

type AddGoodsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGoodsResp) Reset() {
	*x = AddGoodsResp{}
	mi := &file_proto_goods_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGoodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodsResp) ProtoMessage() {}

func (x *AddGoodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goods_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodsResp.ProtoReflect.Descriptor instead.
func (*AddGoodsResp) Descriptor() ([]byte, []int) {
	return file_proto_goods_proto_rawDescGZIP(), []int{1}
}

func (x *AddGoodsResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// 分页查询商品请求
type GoodsListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsListReq) Reset() {
	*x = GoodsListReq{}
	mi := &file_proto_goods_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsListReq) ProtoMessage() {}

func (x *GoodsListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goods_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsListReq.ProtoReflect.Descriptor instead.
func (*GoodsListReq) Descriptor() ([]byte, []int) {
	return file_proto_goods_proto_rawDescGZIP(), []int{2}
}

func (x *GoodsListReq) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *GoodsListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GoodsListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 列表内每一项结构体，复用给列表和详情
type GoodsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       string                 `protobuf:"bytes,1,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cover         string                 `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	Price         string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	OriginalPrice string                 `protobuf:"bytes,5,opt,name=originalPrice,proto3" json:"originalPrice,omitempty"`
	Sales         int64                  `protobuf:"varint,6,opt,name=sales,proto3" json:"sales,omitempty"`
	CategoryId    int64                  `protobuf:"varint,7,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Status        int64                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsItem) Reset() {
	*x = GoodsItem{}
	mi := &file_proto_goods_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsItem) ProtoMessage() {}

func (x *GoodsItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goods_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsItem.ProtoReflect.Descriptor instead.
func (*GoodsItem) Descriptor() ([]byte, []int) {
	return file_proto_goods_proto_rawDescGZIP(), []int{3}
}

func (x *GoodsItem) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *GoodsItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsItem) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *GoodsItem) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GoodsItem) GetOriginalPrice() string {
	if x != nil {
		return x.OriginalPrice
	}
	return ""
}

func (x *GoodsItem) GetSales() int64 {
	if x != nil {
		return x.Sales
	}
	return 0
}

func (x *GoodsItem) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *GoodsItem) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GoodsListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*GoodsItem           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsListResp) Reset() {
	*x = GoodsListResp{}
	mi := &file_proto_goods_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsListResp) ProtoMessage() {}

func (x *GoodsListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goods_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsListResp.ProtoReflect.Descriptor instead.
func (*GoodsListResp) Descriptor() ([]byte, []int) {
	return file_proto_goods_proto_rawDescGZIP(), []int{4}
}

func (x *GoodsListResp) GetList() []*GoodsItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GoodsListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GoodsDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       string                 `protobuf:"bytes,1,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsDetailReq) Reset() {
	*x = GoodsDetailReq{}
	mi := &file_proto_goods_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsDetailReq) ProtoMessage() {}

func (x *GoodsDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goods_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsDetailReq.ProtoReflect.Descriptor instead.
func (*GoodsDetailReq) Descriptor() ([]byte, []int) {
	return file_proto_goods_proto_rawDescGZIP(), []int{5}
}

func (x *GoodsDetailReq) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

// 商品详情响应
type GoodsDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       string                 `protobuf:"bytes,1,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cover         string                 `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	Price         string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	OriginalPrice string                 `protobuf:"bytes,5,opt,name=originalPrice,proto3" json:"originalPrice,omitempty"`
	Stock         int64                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Sales         int64                  `protobuf:"varint,7,opt,name=sales,proto3" json:"sales,omitempty"`
	Desc          string                 `protobuf:"bytes,8,opt,name=desc,proto3" json:"desc,omitempty"`
	Status        int64                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsDetailResp) Reset() {
	*x = GoodsDetailResp{}
	mi := &file_proto_goods_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsDetailResp) ProtoMessage() {}

func (x *GoodsDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goods_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsDetailResp.ProtoReflect.Descriptor instead.
func (*GoodsDetailResp) Descriptor() ([]byte, []int) {
	return file_proto_goods_proto_rawDescGZIP(), []int{6}
}

func (x *GoodsDetailResp) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *GoodsDetailResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsDetailResp) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *GoodsDetailResp) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GoodsDetailResp) GetOriginalPrice() string {
	if x != nil {
		return x.OriginalPrice
	}
	return ""
}

func (x *GoodsDetailResp) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GoodsDetailResp) GetSales() int64 {
	if x != nil {
		return x.Sales
	}
	return 0
}

func (x *GoodsDetailResp) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *GoodsDetailResp) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type OnOffGoodsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       string                 `protobuf:"bytes,1,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnOffGoodsReq) Reset() {
	*x = OnOffGoodsReq{}
	mi := &file_proto_goods_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnOffGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnOffGoodsReq) ProtoMessage() {}

func (x *OnOffGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goods_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnOffGoodsReq.ProtoReflect.Descriptor instead.
func (*OnOffGoodsReq) Descriptor() ([]byte, []int) {
	return file_proto_goods_proto_rawDescGZIP(), []int{7}
}

func (x *OnOffGoodsReq) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *OnOffGoodsReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type OnOffGoodsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnOffGoodsResp) Reset() {
	*x = OnOffGoodsResp{}
	mi := &file_proto_goods_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnOffGoodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnOffGoodsResp) ProtoMessage() {}

func (x *OnOffGoodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goods_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnOffGoodsResp.ProtoReflect.Descriptor instead.
func (*OnOffGoodsResp) Descriptor() ([]byte, []int) {
	return file_proto_goods_proto_rawDescGZIP(), []int{8}
}

func (x *OnOffGoodsResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type AdminGoodsListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGoodsListReq) Reset() {
	*x = AdminGoodsListReq{}
	mi := &file_proto_goods_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGoodsListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGoodsListReq) ProtoMessage() {}

func (x *AdminGoodsListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goods_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGoodsListReq.ProtoReflect.Descriptor instead.
func (*AdminGoodsListReq) Descriptor() ([]byte, []int) {
	return file_proto_goods_proto_rawDescGZIP(), []int{9}
}

func (x *AdminGoodsListReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AdminGoodsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       string                 `protobuf:"bytes,1,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cover         string                 `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	Price         string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	OriginalPrice string                 `protobuf:"bytes,5,opt,name=originalPrice,proto3" json:"originalPrice,omitempty"`
	Sales         int64                  `protobuf:"varint,6,opt,name=sales,proto3" json:"sales,omitempty"`
	Stock         int64                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	CategoryId    int64                  `protobuf:"varint,8,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	Status        int64                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGoodsItem) Reset() {
	*x = AdminGoodsItem{}
	mi := &file_proto_goods_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGoodsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGoodsItem) ProtoMessage() {}

func (x *AdminGoodsItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goods_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGoodsItem.ProtoReflect.Descriptor instead.
func (*AdminGoodsItem) Descriptor() ([]byte, []int) {
	return file_proto_goods_proto_rawDescGZIP(), []int{10}
}

func (x *AdminGoodsItem) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *AdminGoodsItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminGoodsItem) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *AdminGoodsItem) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *AdminGoodsItem) GetOriginalPrice() string {
	if x != nil {
		return x.OriginalPrice
	}
	return ""
}

func (x *AdminGoodsItem) GetSales() int64 {
	if x != nil {
		return x.Sales
	}
	return 0
}

func (x *AdminGoodsItem) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *AdminGoodsItem) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *AdminGoodsItem) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AdminGoodsListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AdminGoodsItem      `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGoodsListResp) Reset() {
	*x = AdminGoodsListResp{}
	mi := &file_proto_goods_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGoodsListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGoodsListResp) ProtoMessage() {}

func (x *AdminGoodsListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goods_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGoodsListResp.ProtoReflect.Descriptor instead.
func (*AdminGoodsListResp) Descriptor() ([]byte, []int) {
	return file_proto_goods_proto_rawDescGZIP(), []int{11}
}

func (x *AdminGoodsListResp) GetList() []*AdminGoodsItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *AdminGoodsListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_goods_proto protoreflect.FileDescriptor

const file_proto_goods_proto_rawDesc = "" +
	"\n" +
	"\x11proto/goods.proto\x12\x05goods\"\xdb\x01\n" +
	"\vAddGoodsReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05cover\x18\x02 \x01(\tR\x05cover\x12$\n" +
	"\roriginalPrice\x18\x03 \x01(\tR\roriginalPrice\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x03R\x05stock\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x06 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04desc\x18\a \x01(\tR\x04desc\x12\x1c\n" +
	"\townUserId\x18\b \x01(\tR\townUserId\"\x1e\n" +
	"\fAddGoodsResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"^\n" +
	"\fGoodsListReq\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\"\xd9\x01\n" +
	"\tGoodsItem\x12\x18\n" +
	"\agoodsId\x18\x01 \x01(\tR\agoodsId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05cover\x18\x03 \x01(\tR\x05cover\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12$\n" +
	"\roriginalPrice\x18\x05 \x01(\tR\roriginalPrice\x12\x14\n" +
	"\x05sales\x18\x06 \x01(\x03R\x05sales\x12\x1e\n" +
	"\n" +
	"categoryId\x18\a \x01(\x03R\n" +
	"categoryId\x12\x16\n" +
	"\x06status\x18\b \x01(\x03R\x06status\"K\n" +
	"\rGoodsListResp\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.goods.GoodsItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"*\n" +
	"\x0eGoodsDetailReq\x12\x18\n" +
	"\agoodsId\x18\x01 \x01(\tR\agoodsId\"\xe9\x01\n" +
	"\x0fGoodsDetailResp\x12\x18\n" +
	"\agoodsId\x18\x01 \x01(\tR\agoodsId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05cover\x18\x03 \x01(\tR\x05cover\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12$\n" +
	"\roriginalPrice\x18\x05 \x01(\tR\roriginalPrice\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x03R\x05stock\x12\x14\n" +
	"\x05sales\x18\a \x01(\x03R\x05sales\x12\x12\n" +
	"\x04desc\x18\b \x01(\tR\x04desc\x12\x16\n" +
	"\x06status\x18\t \x01(\x03R\x06status\"A\n" +
	"\rOnOffGoodsReq\x12\x18\n" +
	"\agoodsId\x18\x01 \x01(\tR\agoodsId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\" \n" +
	"\x0eOnOffGoodsResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"+\n" +
	"\x11AdminGoodsListReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"\xf4\x01\n" +
	"\x0eAdminGoodsItem\x12\x18\n" +
	"\agoodsId\x18\x01 \x01(\tR\agoodsId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05cover\x18\x03 \x01(\tR\x05cover\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12$\n" +
	"\roriginalPrice\x18\x05 \x01(\tR\roriginalPrice\x12\x14\n" +
	"\x05sales\x18\x06 \x01(\x03R\x05sales\x12\x14\n" +
	"\x05stock\x18\a \x01(\x03R\x05stock\x12\x1e\n" +
	"\n" +
	"categoryId\x18\b \x01(\x03R\n" +
	"categoryId\x12\x16\n" +
	"\x06status\x18\t \x01(\x03R\x06status\"U\n" +
	"\x12AdminGoodsListResp\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.goods.AdminGoodsItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xbd\x02\n" +
	"\x05goods\x129\n" +
	"\fGetGoodsList\x12\x13.goods.GoodsListReq\x1a\x14.goods.GoodsListResp\x12?\n" +
	"\x0eGetGoodsDetail\x12\x15.goods.GoodsDetailReq\x1a\x16.goods.GoodsDetailResp\x123\n" +
	"\bAddGoods\x12\x12.goods.AddGoodsReq\x1a\x13.goods.AddGoodsResp\x129\n" +
	"\n" +
	"OnOffGoods\x12\x14.goods.OnOffGoodsReq\x1a\x15.goods.OnOffGoodsResp\x12H\n" +
	"\x11GetAdminGoodsList\x12\x18.goods.AdminGoodsListReq\x1a\x19.goods.AdminGoodsListRespB\vZ\t./goodsPbb\x06proto3"

var (
	file_proto_goods_proto_rawDescOnce sync.Once
	file_proto_goods_proto_rawDescData []byte
)

func file_proto_goods_proto_rawDescGZIP() []byte {
	file_proto_goods_proto_rawDescOnce.Do(func() {
		file_proto_goods_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_goods_proto_rawDesc), len(file_proto_goods_proto_rawDesc)))
	})
	return file_proto_goods_proto_rawDescData
}

var file_proto_goods_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_goods_proto_goTypes = []any{
	(*AddGoodsReq)(nil),        // 0: goods.AddGoodsReq
	(*AddGoodsResp)(nil),       // 1: goods.AddGoodsResp
	(*GoodsListReq)(nil),       // 2: goods.GoodsListReq
	(*GoodsItem)(nil),          // 3: goods.GoodsItem
	(*GoodsListResp)(nil),      // 4: goods.GoodsListResp
	(*GoodsDetailReq)(nil),     // 5: goods.GoodsDetailReq
	(*GoodsDetailResp)(nil),    // 6: goods.GoodsDetailResp
	(*OnOffGoodsReq)(nil),      // 7: goods.OnOffGoodsReq
	(*OnOffGoodsResp)(nil),     // 8: goods.OnOffGoodsResp
	(*AdminGoodsListReq)(nil),  // 9: goods.AdminGoodsListReq
	(*AdminGoodsItem)(nil),     // 10: goods.AdminGoodsItem
	(*AdminGoodsListResp)(nil), // 11: goods.AdminGoodsListResp
}
var file_proto_goods_proto_depIdxs = []int32{
	3,  // 0: goods.GoodsListResp.list:type_name -> goods.GoodsItem
	10, // 1: goods.AdminGoodsListResp.list:type_name -> goods.AdminGoodsItem
	2,  // 2: goods.goods.GetGoodsList:input_type -> goods.GoodsListReq
	5,  // 3: goods.goods.GetGoodsDetail:input_type -> goods.GoodsDetailReq
	0,  // 4: goods.goods.AddGoods:input_type -> goods.AddGoodsReq
	7,  // 5: goods.goods.OnOffGoods:input_type -> goods.OnOffGoodsReq
	9,  // 6: goods.goods.GetAdminGoodsList:input_type -> goods.AdminGoodsListReq
	4,  // 7: goods.goods.GetGoodsList:output_type -> goods.GoodsListResp
	6,  // 8: goods.goods.GetGoodsDetail:output_type -> goods.GoodsDetailResp
	1,  // 9: goods.goods.AddGoods:output_type -> goods.AddGoodsResp
	8,  // 10: goods.goods.OnOffGoods:output_type -> goods.OnOffGoodsResp
	11, // 11: goods.goods.GetAdminGoodsList:output_type -> goods.AdminGoodsListResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_goods_proto_init() }
func file_proto_goods_proto_init() {
	if File_proto_goods_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_goods_proto_rawDesc), len(file_proto_goods_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_goods_proto_goTypes,
		DependencyIndexes: file_proto_goods_proto_depIdxs,
		MessageInfos:      file_proto_goods_proto_msgTypes,
	}.Build()
	File_proto_goods_proto = out.File
	file_proto_goods_proto_goTypes = nil
	file_proto_goods_proto_depIdxs = nil
}
