// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: pay.proto

package pay

import (
	"context"

	"zeromall/pay/rpc/payPb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreatePayReq  = payPb.CreatePayReq
	CreatePayResp = payPb.CreatePayResp

	Pay interface {
		CreatePay(ctx context.Context, in *CreatePayReq, opts ...grpc.CallOption) (*CreatePayResp, error)
	}

	defaultPay struct {
		cli zrpc.Client
	}
)

func NewPay(cli zrpc.Client) Pay {
	return &defaultPay{
		cli: cli,
	}
}

func (m *defaultPay) CreatePay(ctx context.Context, in *CreatePayReq, opts ...grpc.CallOption) (*CreatePayResp, error) {
	client := payPb.NewPayClient(m.cli.Conn())
	return client.CreatePay(ctx, in, opts...)
}
