// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cartFieldNames          = builder.RawFieldNames(&Cart{})
	cartRows                = strings.Join(cartFieldNames, ",")
	cartRowsExpectAutoSet   = strings.Join(stringx.Remove(cartFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cartRowsWithPlaceHolder = strings.Join(stringx.Remove(cartFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	cartModel interface {
		Insert(ctx context.Context, data *Cart) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Cart, error)
		FindOneByUserIdGoodsId(ctx context.Context, userId string, goodsId string) (*Cart, error)
		Update(ctx context.Context, data *Cart) error
		Delete(ctx context.Context, id int64) error
		FindCartsByUserId(ctx context.Context, userId string) ([]*Cart, error)
		TransactCtx(ctx context.Context, userId string, toUpdate []*Cart, toInsert []*Cart, toDelete []string) error
	}

	defaultCartModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Cart struct {
		Id        int64     `db:"id"`         // 本表主键
		UserId    string    `db:"user_id"`    // 用户ID（来自user‑rpc）
		GoodsId   string    `db:"goods_id"`   // 商品UUID字符串
		Num       int64     `db:"num"`        // 购买数量
		Selected  int64     `db:"selected"`   // 0未勾选 1勾选结算
		PriceCent int64     `db:"price_cent"` // 加购时的价格
		Name      string    `db:"name"`
		Cover     string    `db:"cover"`
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newCartModel(conn sqlx.SqlConn) *defaultCartModel {
	return &defaultCartModel{
		conn:  conn,
		table: "`cart`",
	}
}

func (m *defaultCartModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCartModel) FindOne(ctx context.Context, id int64) (*Cart, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cartRows, m.table)
	var resp Cart
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCartModel) FindOneByUserIdGoodsId(ctx context.Context, userId string, goodsId string) (*Cart, error) {
	var resp Cart
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `goods_id` = ? limit 1", cartRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, goodsId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCartModel) Insert(ctx context.Context, data *Cart) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, cartRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.GoodsId, data.Num, data.Selected, data.PriceCent, data.Name, data.Cover)
	return ret, err
}

func (m *defaultCartModel) Update(ctx context.Context, newData *Cart) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cartRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.GoodsId, newData.Num, newData.Selected, newData.PriceCent, newData.Name, newData.Cover, newData.Id)
	return err
}

func (m *defaultCartModel) tableName() string {
	return m.table
}
