// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	payFieldNames          = builder.RawFieldNames(&Pay{})
	payRows                = strings.Join(payFieldNames, ",")
	payRowsExpectAutoSet   = strings.Join(stringx.Remove(payFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	payRowsWithPlaceHolder = strings.Join(stringx.Remove(payFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	payModel interface {
		Insert(ctx context.Context, data *Pay) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Pay, error)
		FindOneByPayNo(ctx context.Context, payNo string) (*Pay, error)
		Update(ctx context.Context, data *Pay) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPayModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Pay struct {
		Id          int64          `db:"id"`
		OrderNo     int64          `db:"order_no"`     // 业务订单号
		PayNo       string         `db:"pay_no"`       // 支付内部流水号雪花
		TradeNo     sql.NullString `db:"trade_no"`     // 第三方交易号，余额支付留空
		PayType     int64          `db:"pay_type"`     // 1余额
		PayCent     int64          `db:"pay_cent"`     // 支付金额(分)
		Status      int64          `db:"status"`       // 0待支付 1支付成功 2支付失败 3已退款
		CallbackRaw sql.NullString `db:"callback_raw"` // 第三方回调报文，余额支付为空
		PayTime     time.Time      `db:"pay_time"`
		CreatedAt   time.Time      `db:"created_at"`
		UpdatedAt   time.Time      `db:"updated_at"`
		UserId      string         `db:"user_id"`
	}
)

func newPayModel(conn sqlx.SqlConn) *defaultPayModel {
	return &defaultPayModel{
		conn:  conn,
		table: "`pay`",
	}
}

func (m *defaultPayModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPayModel) FindOne(ctx context.Context, id int64) (*Pay, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", payRows, m.table)
	var resp Pay
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPayModel) FindOneByPayNo(ctx context.Context, payNo string) (*Pay, error) {
	var resp Pay
	query := fmt.Sprintf("select %s from %s where `pay_no` = ? limit 1", payRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, payNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPayModel) Insert(ctx context.Context, data *Pay) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, payRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OrderNo, data.PayNo, data.TradeNo, data.PayType, data.PayCent, data.Status, data.CallbackRaw, data.PayTime, data.UserId)
	return ret, err
}

func (m *defaultPayModel) Update(ctx context.Context, newData *Pay) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, payRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.OrderNo, newData.PayNo, newData.TradeNo, newData.PayType, newData.PayCent, newData.Status, newData.CallbackRaw, newData.PayTime, newData.UserId, newData.Id)
	return err
}

func (m *defaultPayModel) tableName() string {
	return m.table
}
