// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AddGoodsReq struct {
	Name          string `json:"name"`
	Cover         string `json:"cover"`
	OriginalPrice string `json:"originalPrice"`
	Price         string `json:"price"`
	Stock         int64  `json:"stock"`
	CategoryId    int64  `json:"categoryId"`
	Desc          string `json:"desc"`
}

type GoodsDetailReq struct {
	GoodsId string `path:"goodsId"`
}

type GoodsDetailResp struct {
	GoodsId       string `json:"goodsId"`
	Name          string `json:"name"`
	Cover         string `json:"cover"`
	Price         string `json:"price"`
	OriginalPrice string `json:"originalPrice"`
	Sales         int64  `json:"sales"`
	Desc          string `json:"desc"`
	Status        int64  `json:"status"`
}

type GoodsItem struct {
	GoodsId       string `json:"goodsId"`
	Name          string `json:"name"`
	Cover         string `json:"cover"`
	Price         string `json:"price"`
	OriginalPrice string `json:"originalPrice"`
	Sales         int64  `json:"sales"`
	CategoryId    int64  `json:"categoryId"`
	Status        int64  `json:"status"`
}

type GoodsListReq struct {
	CategoryId int64 `form:"categoryId"` // 分类id，0代表全部分类
	Page       int32 `form:"page,default=1"`
	PageSize   int32 `form:"pageSize,default=10"`
}

type GoodsListResp struct {
	List  []*GoodsItem `json:"list"`
	Total int64        `json:"total"`
}

type OnOffGoodsReq struct {
	GoodsId string `json:"goodsId"`
	Status  int64  `path:"status"`
}

type SelfGoodsItem struct {
	GoodsId       string `json:"goodsId"`
	Name          string `json:"name"`
	Cover         string `json:"cover"`
	Price         string `json:"price"`
	OriginalPrice string `json:"originalPrice"`
	Stock         int64  `json:"stone"`
	Sales         int64  `json:"sales"`
	CategoryId    int64  `json:"categoryId"`
	Status        int64  `json:"status"`
}

type SelfGoodsListResp struct {
	List  []*SelfGoodsItem `json:"list"`
	Total int64            `json:"total"`
}

type UpdateStock struct {
	GoodsId string `json:"goodsId"`
	Num     int64  `json:"num"`
}
