// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/balance.proto

package balancePb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeductBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PayCent       int64                  `protobuf:"varint,2,opt,name=payCent,proto3" json:"payCent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductBalanceReq) Reset() {
	*x = DeductBalanceReq{}
	mi := &file_proto_balance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductBalanceReq) ProtoMessage() {}

func (x *DeductBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_balance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductBalanceReq.ProtoReflect.Descriptor instead.
func (*DeductBalanceReq) Descriptor() ([]byte, []int) {
	return file_proto_balance_proto_rawDescGZIP(), []int{0}
}

func (x *DeductBalanceReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeductBalanceReq) GetPayCent() int64 {
	if x != nil {
		return x.PayCent
	}
	return 0
}

type DeductBalanceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductBalanceResp) Reset() {
	*x = DeductBalanceResp{}
	mi := &file_proto_balance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductBalanceResp) ProtoMessage() {}

func (x *DeductBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_balance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductBalanceResp.ProtoReflect.Descriptor instead.
func (*DeductBalanceResp) Descriptor() ([]byte, []int) {
	return file_proto_balance_proto_rawDescGZIP(), []int{1}
}

func (x *DeductBalanceResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RefundBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PayCent       int64                  `protobuf:"varint,2,opt,name=payCent,proto3" json:"payCent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundBalanceReq) Reset() {
	*x = RefundBalanceReq{}
	mi := &file_proto_balance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundBalanceReq) ProtoMessage() {}

func (x *RefundBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_balance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundBalanceReq.ProtoReflect.Descriptor instead.
func (*RefundBalanceReq) Descriptor() ([]byte, []int) {
	return file_proto_balance_proto_rawDescGZIP(), []int{2}
}

func (x *RefundBalanceReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RefundBalanceReq) GetPayCent() int64 {
	if x != nil {
		return x.PayCent
	}
	return 0
}

type RefundBalanceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundBalanceResp) Reset() {
	*x = RefundBalanceResp{}
	mi := &file_proto_balance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundBalanceResp) ProtoMessage() {}

func (x *RefundBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_balance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundBalanceResp.ProtoReflect.Descriptor instead.
func (*RefundBalanceResp) Descriptor() ([]byte, []int) {
	return file_proto_balance_proto_rawDescGZIP(), []int{3}
}

func (x *RefundBalanceResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_balance_proto protoreflect.FileDescriptor

const file_proto_balance_proto_rawDesc = "" +
	"\n" +
	"\x13proto/balance.proto\x12\abalance\"D\n" +
	"\x10DeductBalanceReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\apayCent\x18\x02 \x01(\x03R\apayCent\"#\n" +
	"\x11DeductBalanceResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"D\n" +
	"\x10RefundBalanceReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\apayCent\x18\x02 \x01(\x03R\apayCent\"#\n" +
	"\x11RefundBalanceResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\x99\x01\n" +
	"\aBalance\x12F\n" +
	"\rdeductBalance\x12\x19.balance.DeductBalanceReq\x1a\x1a.balance.DeductBalanceResp\x12F\n" +
	"\rrefundBalance\x12\x19.balance.RefundBalanceReq\x1a\x1a.balance.RefundBalanceRespB\rZ\v./balancePbb\x06proto3"

var (
	file_proto_balance_proto_rawDescOnce sync.Once
	file_proto_balance_proto_rawDescData []byte
)

func file_proto_balance_proto_rawDescGZIP() []byte {
	file_proto_balance_proto_rawDescOnce.Do(func() {
		file_proto_balance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_balance_proto_rawDesc), len(file_proto_balance_proto_rawDesc)))
	})
	return file_proto_balance_proto_rawDescData
}

var file_proto_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_balance_proto_goTypes = []any{
	(*DeductBalanceReq)(nil),  // 0: balance.DeductBalanceReq
	(*DeductBalanceResp)(nil), // 1: balance.DeductBalanceResp
	(*RefundBalanceReq)(nil),  // 2: balance.RefundBalanceReq
	(*RefundBalanceResp)(nil), // 3: balance.RefundBalanceResp
}
var file_proto_balance_proto_depIdxs = []int32{
	0, // 0: balance.Balance.deductBalance:input_type -> balance.DeductBalanceReq
	2, // 1: balance.Balance.refundBalance:input_type -> balance.RefundBalanceReq
	1, // 2: balance.Balance.deductBalance:output_type -> balance.DeductBalanceResp
	3, // 3: balance.Balance.refundBalance:output_type -> balance.RefundBalanceResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_balance_proto_init() }
func file_proto_balance_proto_init() {
	if File_proto_balance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_balance_proto_rawDesc), len(file_proto_balance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_balance_proto_goTypes,
		DependencyIndexes: file_proto_balance_proto_depIdxs,
		MessageInfos:      file_proto_balance_proto_msgTypes,
	}.Build()
	File_proto_balance_proto = out.File
	file_proto_balance_proto_goTypes = nil
	file_proto_balance_proto_depIdxs = nil
}
