// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/balance.proto

package balancePb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Balance_DeductBalance_FullMethodName = "/balance.Balance/deductBalance"
	Balance_RefundBalance_FullMethodName = "/balance.Balance/refundBalance"
)

// BalanceClient is the client API for Balance service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BalanceClient interface {
	DeductBalance(ctx context.Context, in *DeductBalanceReq, opts ...grpc.CallOption) (*DeductBalanceResp, error)
	RefundBalance(ctx context.Context, in *RefundBalanceReq, opts ...grpc.CallOption) (*RefundBalanceResp, error)
}

type balanceClient struct {
	cc grpc.ClientConnInterface
}

func NewBalanceClient(cc grpc.ClientConnInterface) BalanceClient {
	return &balanceClient{cc}
}

func (c *balanceClient) DeductBalance(ctx context.Context, in *DeductBalanceReq, opts ...grpc.CallOption) (*DeductBalanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeductBalanceResp)
	err := c.cc.Invoke(ctx, Balance_DeductBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceClient) RefundBalance(ctx context.Context, in *RefundBalanceReq, opts ...grpc.CallOption) (*RefundBalanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundBalanceResp)
	err := c.cc.Invoke(ctx, Balance_RefundBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceServer is the server API for Balance service.
// All implementations must embed UnimplementedBalanceServer
// for forward compatibility.
type BalanceServer interface {
	DeductBalance(context.Context, *DeductBalanceReq) (*DeductBalanceResp, error)
	RefundBalance(context.Context, *RefundBalanceReq) (*RefundBalanceResp, error)
	mustEmbedUnimplementedBalanceServer()
}

// UnimplementedBalanceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBalanceServer struct{}

func (UnimplementedBalanceServer) DeductBalance(context.Context, *DeductBalanceReq) (*DeductBalanceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeductBalance not implemented")
}
func (UnimplementedBalanceServer) RefundBalance(context.Context, *RefundBalanceReq) (*RefundBalanceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RefundBalance not implemented")
}
func (UnimplementedBalanceServer) mustEmbedUnimplementedBalanceServer() {}
func (UnimplementedBalanceServer) testEmbeddedByValue()                 {}

// UnsafeBalanceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BalanceServer will
// result in compilation errors.
type UnsafeBalanceServer interface {
	mustEmbedUnimplementedBalanceServer()
}

func RegisterBalanceServer(s grpc.ServiceRegistrar, srv BalanceServer) {
	// If the following call panics, it indicates UnimplementedBalanceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Balance_ServiceDesc, srv)
}

func _Balance_DeductBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).DeductBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Balance_DeductBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).DeductBalance(ctx, req.(*DeductBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Balance_RefundBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceServer).RefundBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Balance_RefundBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceServer).RefundBalance(ctx, req.(*RefundBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Balance_ServiceDesc is the grpc.ServiceDesc for Balance service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Balance_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "balance.Balance",
	HandlerType: (*BalanceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "deductBalance",
			Handler:    _Balance_DeductBalance_Handler,
		},
		{
			MethodName: "refundBalance",
			Handler:    _Balance_RefundBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/balance.proto",
}
