// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: pay.proto

package server

import (
	"context"

	"zeromall/pay/rpc/internal/logic"
	"zeromall/pay/rpc/internal/svc"
	"zeromall/pay/rpc/payPb"
)

type PayServer struct {
	svcCtx *svc.ServiceContext
	payPb.UnimplementedPayServer
}

func NewPayServer(svcCtx *svc.ServiceContext) *PayServer {
	return &PayServer{
		svcCtx: svcCtx,
	}
}

func (s *PayServer) CreatePay(ctx context.Context, in *payPb.CreatePayReq) (*payPb.CreatePayResp, error) {
	l := logic.NewCreatePayLogic(ctx, s.svcCtx)
	return l.CreatePay(in)
}
