// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: stock.proto

package server

import (
	"context"

	"zeromall/stock/rpc/internal/logic"
	"zeromall/stock/rpc/internal/svc"
	"zeromall/stock/rpc/stockPb"
)

type StockServer struct {
	svcCtx *svc.ServiceContext
	stockPb.UnimplementedStockServer
}

func NewStockServer(svcCtx *svc.ServiceContext) *StockServer {
	return &StockServer{
		svcCtx: svcCtx,
	}
}

func (s *StockServer) InsertStock(ctx context.Context, in *stockPb.InsertStockReq) (*stockPb.InsertStockResp, error) {
	l := logic.NewInsertStockLogic(ctx, s.svcCtx)
	return l.InsertStock(in)
}

func (s *StockServer) GetStock(ctx context.Context, in *stockPb.GetStockReq) (*stockPb.GetStockResp, error) {
	l := logic.NewGetStockLogic(ctx, s.svcCtx)
	return l.GetStock(in)
}

func (s *StockServer) PreHeatStock(ctx context.Context, in *stockPb.PreHeatStockReq) (*stockPb.PreHeatStockResp, error) {
	l := logic.NewPreHeatStockLogic(ctx, s.svcCtx)
	return l.PreHeatStock(in)
}
