// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"zeromall/user/rpc/internal/logic"
	"zeromall/user/rpc/internal/svc"
	"zeromall/user/rpc/userpb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	userpb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *userpb.RegisterReq) (*userpb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *userpb.LoginReq) (*userpb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Captcha(ctx context.Context, in *userpb.CaptchaReq) (*userpb.CaptchaResp, error) {
	l := logic.NewCaptchaLogic(ctx, s.svcCtx)
	return l.Captcha(in)
}

func (s *UserServer) UserInfo(ctx context.Context, in *userpb.UserInfoReq) (*userpb.UserInfoResp, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}

func (s *UserServer) ChangeInfo(ctx context.Context, in *userpb.ChangeInfoReq) (*userpb.ChangeInfoResp, error) {
	l := logic.NewChangeInfoLogic(ctx, s.svcCtx)
	return l.ChangeInfo(in)
}

func (s *UserServer) GetRegion(ctx context.Context, in *userpb.GetRegionReq) (*userpb.GetRegionResp, error) {
	l := logic.NewGetRegionLogic(ctx, s.svcCtx)
	return l.GetRegion(in)
}

func (s *UserServer) GetSellPower(ctx context.Context, in *userpb.GetSellPowerReq) (*userpb.GetSellPowerResp, error) {
	l := logic.NewGetSellPowerLogic(ctx, s.svcCtx)
	return l.GetSellPower(in)
}
