// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: cart.proto

package server

import (
	"context"

	"zeromall/cart/rpc/cartPb"
	"zeromall/cart/rpc/internal/logic"
	"zeromall/cart/rpc/internal/svc"
)

type CartServer struct {
	svcCtx *svc.ServiceContext
	cartPb.UnimplementedCartServer
}

func NewCartServer(svcCtx *svc.ServiceContext) *CartServer {
	return &CartServer{
		svcCtx: svcCtx,
	}
}

func (s *CartServer) AddCart(ctx context.Context, in *cartPb.AddCartReq) (*cartPb.AddCartResp, error) {
	l := logic.NewAddCartLogic(ctx, s.svcCtx)
	return l.AddCart(in)
}

func (s *CartServer) GetCartList(ctx context.Context, in *cartPb.GetCartListReq) (*cartPb.GetCartListResp, error) {
	l := logic.NewGetCartListLogic(ctx, s.svcCtx)
	return l.GetCartList(in)
}

func (s *CartServer) UpdateCart(ctx context.Context, in *cartPb.UpdateCartReq) (*cartPb.UpdateCartResp, error) {
	l := logic.NewUpdateCartLogic(ctx, s.svcCtx)
	return l.UpdateCart(in)
}

func (s *CartServer) BatchDelete(ctx context.Context, in *cartPb.BatchDeleteReq) (*cartPb.BatchDeleteResp, error) {
	l := logic.NewBatchDeleteLogic(ctx, s.svcCtx)
	return l.BatchDelete(in)
}
