// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: balance.proto

package server

import (
	"context"

	"zeromall/balance/rpc/balancePb"
	"zeromall/balance/rpc/internal/logic"
	"zeromall/balance/rpc/internal/svc"
)

type BalanceServer struct {
	svcCtx *svc.ServiceContext
	balancePb.UnimplementedBalanceServer
}

func NewBalanceServer(svcCtx *svc.ServiceContext) *BalanceServer {
	return &BalanceServer{
		svcCtx: svcCtx,
	}
}

func (s *BalanceServer) DeductBalance(ctx context.Context, in *balancePb.DeductBalanceReq) (*balancePb.DeductBalanceResp, error) {
	l := logic.NewDeductBalanceLogic(ctx, s.svcCtx)
	return l.DeductBalance(in)
}

func (s *BalanceServer) RefundBalance(ctx context.Context, in *balancePb.RefundBalanceReq) (*balancePb.RefundBalanceResp, error) {
	l := logic.NewRefundBalanceLogic(ctx, s.svcCtx)
	return l.RefundBalance(in)
}
