// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/pay.proto

package payPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       int64                  `protobuf:"varint,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	PayCent       int64                  `protobuf:"varint,3,opt,name=payCent,proto3" json:"payCent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePayReq) Reset() {
	*x = CreatePayReq{}
	mi := &file_proto_pay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePayReq) ProtoMessage() {}

func (x *CreatePayReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePayReq.ProtoReflect.Descriptor instead.
func (*CreatePayReq) Descriptor() ([]byte, []int) {
	return file_proto_pay_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePayReq) GetOrderNo() int64 {
	if x != nil {
		return x.OrderNo
	}
	return 0
}

func (x *CreatePayReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePayReq) GetPayCent() int64 {
	if x != nil {
		return x.PayCent
	}
	return 0
}

type CreatePayResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePayResp) Reset() {
	*x = CreatePayResp{}
	mi := &file_proto_pay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePayResp) ProtoMessage() {}

func (x *CreatePayResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePayResp.ProtoReflect.Descriptor instead.
func (*CreatePayResp) Descriptor() ([]byte, []int) {
	return file_proto_pay_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePayResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_pay_proto protoreflect.FileDescriptor

const file_proto_pay_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/pay.proto\x12\x03pay\"Z\n" +
	"\fCreatePayReq\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\x03R\aorderNo\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\apayCent\x18\x03 \x01(\x03R\apayCent\"\x1f\n" +
	"\rCreatePayResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok29\n" +
	"\x03Pay\x122\n" +
	"\tcreatePay\x12\x11.pay.CreatePayReq\x1a\x12.pay.CreatePayRespB\tZ\a./payPbb\x06proto3"

var (
	file_proto_pay_proto_rawDescOnce sync.Once
	file_proto_pay_proto_rawDescData []byte
)

func file_proto_pay_proto_rawDescGZIP() []byte {
	file_proto_pay_proto_rawDescOnce.Do(func() {
		file_proto_pay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pay_proto_rawDesc), len(file_proto_pay_proto_rawDesc)))
	})
	return file_proto_pay_proto_rawDescData
}

var file_proto_pay_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_pay_proto_goTypes = []any{
	(*CreatePayReq)(nil),  // 0: pay.CreatePayReq
	(*CreatePayResp)(nil), // 1: pay.CreatePayResp
}
var file_proto_pay_proto_depIdxs = []int32{
	0, // 0: pay.Pay.createPay:input_type -> pay.CreatePayReq
	1, // 1: pay.Pay.createPay:output_type -> pay.CreatePayResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pay_proto_init() }
func file_proto_pay_proto_init() {
	if File_proto_pay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pay_proto_rawDesc), len(file_proto_pay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pay_proto_goTypes,
		DependencyIndexes: file_proto_pay_proto_depIdxs,
		MessageInfos:      file_proto_pay_proto_msgTypes,
	}.Build()
	File_proto_pay_proto = out.File
	file_proto_pay_proto_goTypes = nil
	file_proto_pay_proto_depIdxs = nil
}
