// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: goods.proto

package server

import (
	"context"

	"zeromall/goods/rpc/goodsPb"
	"zeromall/goods/rpc/internal/logic"
	"zeromall/goods/rpc/internal/svc"
)

type GoodsServer struct {
	svcCtx *svc.ServiceContext
	goodsPb.UnimplementedGoodsServer
}

func NewGoodsServer(svcCtx *svc.ServiceContext) *GoodsServer {
	return &GoodsServer{
		svcCtx: svcCtx,
	}
}

func (s *GoodsServer) GetGoodsList(ctx context.Context, in *goodsPb.GoodsListReq) (*goodsPb.GoodsListResp, error) {
	l := logic.NewGetGoodsListLogic(ctx, s.svcCtx)
	return l.GetGoodsList(in)
}

func (s *GoodsServer) GetGoodsDetail(ctx context.Context, in *goodsPb.GoodsDetailReq) (*goodsPb.GoodsDetailResp, error) {
	l := logic.NewGetGoodsDetailLogic(ctx, s.svcCtx)
	return l.GetGoodsDetail(in)
}

func (s *GoodsServer) AddGoods(ctx context.Context, in *goodsPb.AddGoodsReq) (*goodsPb.AddGoodsResp, error) {
	l := logic.NewAddGoodsLogic(ctx, s.svcCtx)
	return l.AddGoods(in)
}

func (s *GoodsServer) OnOffGoods(ctx context.Context, in *goodsPb.OnOffGoodsReq) (*goodsPb.OnOffGoodsResp, error) {
	l := logic.NewOnOffGoodsLogic(ctx, s.svcCtx)
	return l.OnOffGoods(in)
}

func (s *GoodsServer) GetAdminGoodsList(ctx context.Context, in *goodsPb.AdminGoodsListReq) (*goodsPb.AdminGoodsListResp, error) {
	l := logic.NewGetAdminGoodsListLogic(ctx, s.svcCtx)
	return l.GetAdminGoodsList(in)
}
