// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"zeromall/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/order",
				Handler: createOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/order/detail/:orderNo",
				Handler: getOrderDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/preview",
				Handler: previewOrderHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
