// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"zeromall/cart/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/cart/add",
				Handler: AddCartHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/cart/item",
				Handler: UpdateCartHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/cart/items",
				Handler: BatchDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/cart/list",
				Handler: GetCartListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
