// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: stock.proto

package stock

import (
	"context"

	"zeromall/stock/rpc/stockPb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetStockReq     = stockPb.GetStockReq
	GetStockResp    = stockPb.GetStockResp
	InsertStockReq  = stockPb.InsertStockReq
	InsertStockResp = stockPb.InsertStockResp

	Stock interface {
		InsertStock(ctx context.Context, in *InsertStockReq, opts ...grpc.CallOption) (*InsertStockResp, error)
		GetStock(ctx context.Context, in *GetStockReq, opts ...grpc.CallOption) (*GetStockResp, error)
	}

	defaultStock struct {
		cli zrpc.Client
	}
)

func NewStock(cli zrpc.Client) Stock {
	return &defaultStock{
		cli: cli,
	}
}

func (m *defaultStock) InsertStock(ctx context.Context, in *InsertStockReq, opts ...grpc.CallOption) (*InsertStockResp, error) {
	client := stockPb.NewStockClient(m.cli.Conn())
	return client.InsertStock(ctx, in, opts...)
}

func (m *defaultStock) GetStock(ctx context.Context, in *GetStockReq, opts ...grpc.CallOption) (*GetStockResp, error) {
	client := stockPb.NewStockClient(m.cli.Conn())
	return client.GetStock(ctx, in, opts...)
}
