// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"zeromall/goods/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/goods/detail/:goodsId",
				Handler: GetGoodsDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/goods/list",
				Handler: GetGoodsListHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/goods",
				Handler: AddGoodsHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/goods/:status",
				Handler: OnOffGoodsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/goods/self",
				Handler: GetAdminGoodsListHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/goods/stock",
				Handler: UpdateStockHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
