// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	balanceFieldNames          = builder.RawFieldNames(&Balance{})
	balanceRows                = strings.Join(balanceFieldNames, ",")
	balanceRowsExpectAutoSet   = strings.Join(stringx.Remove(balanceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	balanceRowsWithPlaceHolder = strings.Join(stringx.Remove(balanceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	balanceModel interface {
		Insert(ctx context.Context, data *Balance) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Balance, error)
		FindOneByUserId(ctx context.Context, userId string) (*Balance, error)
		Update(ctx context.Context, data *Balance) error
		Delete(ctx context.Context, id int64) error
		DeductBalance(ctx context.Context, payCent int64, version int64, userId string) (int64, error)
		RefundBalance(ctx context.Context, payCent int64, userId string) (int64, error)
	}

	defaultBalanceModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Balance struct {
		Id            int64     `db:"id"`
		UserId        string    `db:"user_id"`
		AvailableCent int64     `db:"available_cent"`
		Version       int64     `db:"version"`
		UpdatedAt     time.Time `db:"updated_at"`
	}
)

func newBalanceModel(conn sqlx.SqlConn) *defaultBalanceModel {
	return &defaultBalanceModel{
		conn:  conn,
		table: "`balance`",
	}
}

func (m *defaultBalanceModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBalanceModel) FindOne(ctx context.Context, id int64) (*Balance, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", balanceRows, m.table)
	var resp Balance
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBalanceModel) FindOneByUserId(ctx context.Context, userId string) (*Balance, error) {
	var resp Balance
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", balanceRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBalanceModel) Insert(ctx context.Context, data *Balance) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, balanceRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.AvailableCent, data.Version)
	return ret, err
}

func (m *defaultBalanceModel) Update(ctx context.Context, newData *Balance) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, balanceRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.AvailableCent, newData.Version, newData.Id)
	return err
}

func (m *defaultBalanceModel) tableName() string {
	return m.table
}
