// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/cart.proto

package cartPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCartListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartListReq) Reset() {
	*x = GetCartListReq{}
	mi := &file_proto_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartListReq) ProtoMessage() {}

func (x *GetCartListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartListReq.ProtoReflect.Descriptor instead.
func (*GetCartListReq) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{0}
}

func (x *GetCartListReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           int64                  `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Selected      int64                  `protobuf:"varint,2,opt,name=selected,proto3" json:"selected,omitempty"`
	GoodsId       string                 `protobuf:"bytes,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Cover         string                 `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	Price         string                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_proto_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{1}
}

func (x *CartItem) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *CartItem) GetSelected() int64 {
	if x != nil {
		return x.Selected
	}
	return 0
}

func (x *CartItem) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *CartItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CartItem) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *CartItem) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

type CartItemRedis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           int64                  `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Selected      int64                  `protobuf:"varint,2,opt,name=selected,proto3" json:"selected,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Cover         string                 `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Price         string                 `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemRedis) Reset() {
	*x = CartItemRedis{}
	mi := &file_proto_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemRedis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemRedis) ProtoMessage() {}

func (x *CartItemRedis) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemRedis.ProtoReflect.Descriptor instead.
func (*CartItemRedis) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{2}
}

func (x *CartItemRedis) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *CartItemRedis) GetSelected() int64 {
	if x != nil {
		return x.Selected
	}
	return 0
}

func (x *CartItemRedis) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CartItemRedis) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *CartItemRedis) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

type GetCartListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*CartItem            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartListResp) Reset() {
	*x = GetCartListResp{}
	mi := &file_proto_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartListResp) ProtoMessage() {}

func (x *GetCartListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartListResp.ProtoReflect.Descriptor instead.
func (*GetCartListResp) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{3}
}

func (x *GetCartListResp) GetList() []*CartItem {
	if x != nil {
		return x.List
	}
	return nil
}

type AddCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId       string                 `protobuf:"bytes,2,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	AddNum        int64                  `protobuf:"varint,3,opt,name=addNum,proto3" json:"addNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCartReq) Reset() {
	*x = AddCartReq{}
	mi := &file_proto_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCartReq) ProtoMessage() {}

func (x *AddCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCartReq.ProtoReflect.Descriptor instead.
func (*AddCartReq) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{4}
}

func (x *AddCartReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddCartReq) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *AddCartReq) GetAddNum() int64 {
	if x != nil {
		return x.AddNum
	}
	return 0
}

type AddCartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCartResp) Reset() {
	*x = AddCartResp{}
	mi := &file_proto_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCartResp) ProtoMessage() {}

func (x *AddCartResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCartResp.ProtoReflect.Descriptor instead.
func (*AddCartResp) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{5}
}

func (x *AddCartResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type UpdateCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId       string                 `protobuf:"bytes,2,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Num           int64                  `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	Selected      int64                  `protobuf:"varint,4,opt,name=selected,proto3" json:"selected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartReq) Reset() {
	*x = UpdateCartReq{}
	mi := &file_proto_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartReq) ProtoMessage() {}

func (x *UpdateCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartReq.ProtoReflect.Descriptor instead.
func (*UpdateCartReq) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCartReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateCartReq) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *UpdateCartReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *UpdateCartReq) GetSelected() int64 {
	if x != nil {
		return x.Selected
	}
	return 0
}

type UpdateCartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       string                 `protobuf:"bytes,1,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Num           int64                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Selected      int64                  `protobuf:"varint,3,opt,name=selected,proto3" json:"selected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartResp) Reset() {
	*x = UpdateCartResp{}
	mi := &file_proto_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartResp) ProtoMessage() {}

func (x *UpdateCartResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartResp.ProtoReflect.Descriptor instead.
func (*UpdateCartResp) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCartResp) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *UpdateCartResp) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *UpdateCartResp) GetSelected() int64 {
	if x != nil {
		return x.Selected
	}
	return 0
}

type BatchDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsIds      []string               `protobuf:"bytes,2,rep,name=goodsIds,proto3" json:"goodsIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteReq) Reset() {
	*x = BatchDeleteReq{}
	mi := &file_proto_cart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteReq) ProtoMessage() {}

func (x *BatchDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteReq.ProtoReflect.Descriptor instead.
func (*BatchDeleteReq) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{8}
}

func (x *BatchDeleteReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BatchDeleteReq) GetGoodsIds() []string {
	if x != nil {
		return x.GoodsIds
	}
	return nil
}

type BatchDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteResp) Reset() {
	*x = BatchDeleteResp{}
	mi := &file_proto_cart_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteResp) ProtoMessage() {}

func (x *BatchDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteResp.ProtoReflect.Descriptor instead.
func (*BatchDeleteResp) Descriptor() ([]byte, []int) {
	return file_proto_cart_proto_rawDescGZIP(), []int{9}
}

func (x *BatchDeleteResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_cart_proto protoreflect.FileDescriptor

const file_proto_cart_proto_rawDesc = "" +
	"\n" +
	"\x10proto/cart.proto\x12\x04cart\"(\n" +
	"\x0eGetCartListReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"\x92\x01\n" +
	"\bCartItem\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x03R\x03num\x12\x1a\n" +
	"\bselected\x18\x02 \x01(\x03R\bselected\x12\x18\n" +
	"\agoodsId\x18\x03 \x01(\tR\agoodsId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05cover\x18\x05 \x01(\tR\x05cover\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\"}\n" +
	"\rCartItemRedis\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x03R\x03num\x12\x1a\n" +
	"\bselected\x18\x02 \x01(\x03R\bselected\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05cover\x18\x04 \x01(\tR\x05cover\x12\x14\n" +
	"\x05price\x18\x05 \x01(\tR\x05price\"5\n" +
	"\x0fGetCartListResp\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.cart.CartItemR\x04list\"V\n" +
	"\n" +
	"AddCartReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\agoodsId\x18\x02 \x01(\tR\agoodsId\x12\x16\n" +
	"\x06addNum\x18\x03 \x01(\x03R\x06addNum\"\x1d\n" +
	"\vAddCartResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"o\n" +
	"\rUpdateCartReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\agoodsId\x18\x02 \x01(\tR\agoodsId\x12\x10\n" +
	"\x03num\x18\x03 \x01(\x03R\x03num\x12\x1a\n" +
	"\bselected\x18\x04 \x01(\x03R\bselected\"X\n" +
	"\x0eUpdateCartResp\x12\x18\n" +
	"\agoodsId\x18\x01 \x01(\tR\agoodsId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\x12\x1a\n" +
	"\bselected\x18\x03 \x01(\x03R\bselected\"D\n" +
	"\x0eBatchDeleteReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bgoodsIds\x18\x02 \x03(\tR\bgoodsIds\"!\n" +
	"\x0fBatchDeleteResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xe7\x01\n" +
	"\x04Cart\x12.\n" +
	"\aAddCart\x12\x10.cart.AddCartReq\x1a\x11.cart.AddCartResp\x12:\n" +
	"\vGetCartList\x12\x14.cart.GetCartListReq\x1a\x15.cart.GetCartListResp\x127\n" +
	"\n" +
	"UpdateCart\x12\x13.cart.UpdateCartReq\x1a\x14.cart.UpdateCartResp\x12:\n" +
	"\vBatchDelete\x12\x14.cart.BatchDeleteReq\x1a\x15.cart.BatchDeleteRespB\n" +
	"Z\b./cartPbb\x06proto3"

var (
	file_proto_cart_proto_rawDescOnce sync.Once
	file_proto_cart_proto_rawDescData []byte
)

func file_proto_cart_proto_rawDescGZIP() []byte {
	file_proto_cart_proto_rawDescOnce.Do(func() {
		file_proto_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cart_proto_rawDesc), len(file_proto_cart_proto_rawDesc)))
	})
	return file_proto_cart_proto_rawDescData
}

var file_proto_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_cart_proto_goTypes = []any{
	(*GetCartListReq)(nil),  // 0: cart.GetCartListReq
	(*CartItem)(nil),        // 1: cart.CartItem
	(*CartItemRedis)(nil),   // 2: cart.CartItemRedis
	(*GetCartListResp)(nil), // 3: cart.GetCartListResp
	(*AddCartReq)(nil),      // 4: cart.AddCartReq
	(*AddCartResp)(nil),     // 5: cart.AddCartResp
	(*UpdateCartReq)(nil),   // 6: cart.UpdateCartReq
	(*UpdateCartResp)(nil),  // 7: cart.UpdateCartResp
	(*BatchDeleteReq)(nil),  // 8: cart.BatchDeleteReq
	(*BatchDeleteResp)(nil), // 9: cart.BatchDeleteResp
}
var file_proto_cart_proto_depIdxs = []int32{
	1, // 0: cart.GetCartListResp.list:type_name -> cart.CartItem
	4, // 1: cart.Cart.AddCart:input_type -> cart.AddCartReq
	0, // 2: cart.Cart.GetCartList:input_type -> cart.GetCartListReq
	6, // 3: cart.Cart.UpdateCart:input_type -> cart.UpdateCartReq
	8, // 4: cart.Cart.BatchDelete:input_type -> cart.BatchDeleteReq
	5, // 5: cart.Cart.AddCart:output_type -> cart.AddCartResp
	3, // 6: cart.Cart.GetCartList:output_type -> cart.GetCartListResp
	7, // 7: cart.Cart.UpdateCart:output_type -> cart.UpdateCartResp
	9, // 8: cart.Cart.BatchDelete:output_type -> cart.BatchDeleteResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_cart_proto_init() }
func file_proto_cart_proto_init() {
	if File_proto_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cart_proto_rawDesc), len(file_proto_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cart_proto_goTypes,
		DependencyIndexes: file_proto_cart_proto_depIdxs,
		MessageInfos:      file_proto_cart_proto_msgTypes,
	}.Build()
	File_proto_cart_proto = out.File
	file_proto_cart_proto_goTypes = nil
	file_proto_cart_proto_depIdxs = nil
}
