// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Captcha       string                 `protobuf:"bytes,3,opt,name=captcha,proto3" json:"captcha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *LoginReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CaptchaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptchaReq) Reset() {
	*x = CaptchaReq{}
	mi := &file_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaReq) ProtoMessage() {}

func (x *CaptchaReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaReq.ProtoReflect.Descriptor instead.
func (*CaptchaReq) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *CaptchaReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type CaptchaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Captcha       string                 `protobuf:"bytes,1,opt,name=captcha,proto3" json:"captcha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptchaResp) Reset() {
	*x = CaptchaResp{}
	mi := &file_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaResp) ProtoMessage() {}

func (x *CaptchaResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaResp.ProtoReflect.Descriptor instead.
func (*CaptchaResp) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *CaptchaResp) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

type UserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoReq) Reset() {
	*x = UserInfoReq{}
	mi := &file_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoReq) ProtoMessage() {}

func (x *UserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoReq.ProtoReflect.Descriptor instead.
func (*UserInfoReq) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserInfoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Age           uint64                 `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Sex           uint64                 `protobuf:"varint,6,opt,name=sex,proto3" json:"sex,omitempty"`
	Region        int64                  `protobuf:"varint,7,opt,name=region,proto3" json:"region,omitempty"`
	Balance       string                 `protobuf:"bytes,8,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResp) Reset() {
	*x = UserInfoResp{}
	mi := &file_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResp) ProtoMessage() {}

func (x *UserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResp.ProtoReflect.Descriptor instead.
func (*UserInfoResp) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserInfoResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfoResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfoResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfoResp) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfoResp) GetAge() uint64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserInfoResp) GetSex() uint64 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UserInfoResp) GetRegion() int64 {
	if x != nil {
		return x.Region
	}
	return 0
}

func (x *UserInfoResp) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

type ChangeInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username      *string                `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Avatar        *string                `protobuf:"bytes,3,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	Region        *int64                 `protobuf:"varint,4,opt,name=region,proto3,oneof" json:"region,omitempty"`
	Age           *uint64                `protobuf:"varint,5,opt,name=age,proto3,oneof" json:"age,omitempty"`
	Sex           *uint64                `protobuf:"varint,6,opt,name=sex,proto3,oneof" json:"sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeInfoReq) Reset() {
	*x = ChangeInfoReq{}
	mi := &file_proto_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeInfoReq) ProtoMessage() {}

func (x *ChangeInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeInfoReq.ProtoReflect.Descriptor instead.
func (*ChangeInfoReq) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{8}
}

func (x *ChangeInfoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangeInfoReq) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *ChangeInfoReq) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *ChangeInfoReq) GetRegion() int64 {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return 0
}

func (x *ChangeInfoReq) GetAge() uint64 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *ChangeInfoReq) GetSex() uint64 {
	if x != nil && x.Sex != nil {
		return *x.Sex
	}
	return 0
}

type ChangeInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeInfoResp) Reset() {
	*x = ChangeInfoResp{}
	mi := &file_proto_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeInfoResp) ProtoMessage() {}

func (x *ChangeInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeInfoResp.ProtoReflect.Descriptor instead.
func (*ChangeInfoResp) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeInfoResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetRegionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         *int64                 `protobuf:"varint,1,opt,name=level,proto3,oneof" json:"level,omitempty"`
	Pid           *int64                 `protobuf:"varint,2,opt,name=pid,proto3,oneof" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionReq) Reset() {
	*x = GetRegionReq{}
	mi := &file_proto_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionReq) ProtoMessage() {}

func (x *GetRegionReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionReq.ProtoReflect.Descriptor instead.
func (*GetRegionReq) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{10}
}

func (x *GetRegionReq) GetLevel() int64 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *GetRegionReq) GetPid() int64 {
	if x != nil && x.Pid != nil {
		return *x.Pid
	}
	return 0
}

type RegionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PId           int64                  `protobuf:"varint,2,opt,name=pId,proto3" json:"pId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Level         int64                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionItem) Reset() {
	*x = RegionItem{}
	mi := &file_proto_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionItem) ProtoMessage() {}

func (x *RegionItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionItem.ProtoReflect.Descriptor instead.
func (*RegionItem) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{11}
}

func (x *RegionItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegionItem) GetPId() int64 {
	if x != nil {
		return x.PId
	}
	return 0
}

func (x *RegionItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegionItem) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

type GetRegionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*RegionItem          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegionResp) Reset() {
	*x = GetRegionResp{}
	mi := &file_proto_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegionResp) ProtoMessage() {}

func (x *GetRegionResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegionResp.ProtoReflect.Descriptor instead.
func (*GetRegionResp) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetRegionResp) GetList() []*RegionItem {
	if x != nil {
		return x.List
	}
	return nil
}

type GetSellPowerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSellPowerReq) Reset() {
	*x = GetSellPowerReq{}
	mi := &file_proto_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSellPowerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellPowerReq) ProtoMessage() {}

func (x *GetSellPowerReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellPowerReq.ProtoReflect.Descriptor instead.
func (*GetSellPowerReq) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetSellPowerReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetSellPowerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSellPowerResp) Reset() {
	*x = GetSellPowerResp{}
	mi := &file_proto_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSellPowerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellPowerResp) ProtoMessage() {}

func (x *GetSellPowerResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellPowerResp.ProtoReflect.Descriptor instead.
func (*GetSellPowerResp) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetSellPowerResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_user_proto protoreflect.FileDescriptor

const file_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x10proto/user.proto\x12\x04user\"Y\n" +
	"\vRegisterReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x18\n" +
	"\acaptcha\x18\x03 \x01(\tR\acaptcha\"&\n" +
	"\fRegisterResp\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"<\n" +
	"\bLoginReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"#\n" +
	"\tLoginResp\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"\"\n" +
	"\n" +
	"CaptchaReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"'\n" +
	"\vCaptchaResp\x12\x18\n" +
	"\acaptcha\x18\x01 \x01(\tR\acaptcha\"%\n" +
	"\vUserInfoReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"\xc6\x01\n" +
	"\fUserInfoResp\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x10\n" +
	"\x03age\x18\x05 \x01(\x04R\x03age\x12\x10\n" +
	"\x03sex\x18\x06 \x01(\x04R\x03sex\x12\x16\n" +
	"\x06region\x18\a \x01(\x03R\x06region\x12\x18\n" +
	"\abalance\x18\b \x01(\tR\abalance\"\xe3\x01\n" +
	"\rChangeInfoReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x03 \x01(\tH\x01R\x06avatar\x88\x01\x01\x12\x1b\n" +
	"\x06region\x18\x04 \x01(\x03H\x02R\x06region\x88\x01\x01\x12\x15\n" +
	"\x03age\x18\x05 \x01(\x04H\x03R\x03age\x88\x01\x01\x12\x15\n" +
	"\x03sex\x18\x06 \x01(\x04H\x04R\x03sex\x88\x01\x01B\v\n" +
	"\t_usernameB\t\n" +
	"\a_avatarB\t\n" +
	"\a_regionB\x06\n" +
	"\x04_ageB\x06\n" +
	"\x04_sex\" \n" +
	"\x0eChangeInfoResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"R\n" +
	"\fGetRegionReq\x12\x19\n" +
	"\x05level\x18\x01 \x01(\x03H\x00R\x05level\x88\x01\x01\x12\x15\n" +
	"\x03pid\x18\x02 \x01(\x03H\x01R\x03pid\x88\x01\x01B\b\n" +
	"\x06_levelB\x06\n" +
	"\x04_pid\"X\n" +
	"\n" +
	"RegionItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03pId\x18\x02 \x01(\x03R\x03pId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x03R\x05level\"5\n" +
	"\rGetRegionResp\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.user.RegionItemR\x04list\")\n" +
	"\x0fGetSellPowerReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"\"\n" +
	"\x10GetSellPowerResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xf4\x02\n" +
	"\x04User\x121\n" +
	"\bRegister\x12\x11.user.RegisterReq\x1a\x12.user.RegisterResp\x12(\n" +
	"\x05Login\x12\x0e.user.LoginReq\x1a\x0f.user.LoginResp\x12.\n" +
	"\aCaptcha\x12\x10.user.CaptchaReq\x1a\x11.user.CaptchaResp\x121\n" +
	"\bUserInfo\x12\x11.user.UserInfoReq\x1a\x12.user.UserInfoResp\x127\n" +
	"\n" +
	"ChangeInfo\x12\x13.user.ChangeInfoReq\x1a\x14.user.ChangeInfoResp\x124\n" +
	"\tGetRegion\x12\x12.user.GetRegionReq\x1a\x13.user.GetRegionResp\x12=\n" +
	"\fGetSellPower\x12\x15.user.GetSellPowerReq\x1a\x16.user.GetSellPowerRespB\n" +
	"Z\b./userpbb\x06proto3"

var (
	file_proto_user_proto_rawDescOnce sync.Once
	file_proto_user_proto_rawDescData []byte
)

func file_proto_user_proto_rawDescGZIP() []byte {
	file_proto_user_proto_rawDescOnce.Do(func() {
		file_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)))
	})
	return file_proto_user_proto_rawDescData
}

var file_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_user_proto_goTypes = []any{
	(*RegisterReq)(nil),      // 0: user.RegisterReq
	(*RegisterResp)(nil),     // 1: user.RegisterResp
	(*LoginReq)(nil),         // 2: user.LoginReq
	(*LoginResp)(nil),        // 3: user.LoginResp
	(*CaptchaReq)(nil),       // 4: user.CaptchaReq
	(*CaptchaResp)(nil),      // 5: user.CaptchaResp
	(*UserInfoReq)(nil),      // 6: user.UserInfoReq
	(*UserInfoResp)(nil),     // 7: user.UserInfoResp
	(*ChangeInfoReq)(nil),    // 8: user.ChangeInfoReq
	(*ChangeInfoResp)(nil),   // 9: user.ChangeInfoResp
	(*GetRegionReq)(nil),     // 10: user.GetRegionReq
	(*RegionItem)(nil),       // 11: user.RegionItem
	(*GetRegionResp)(nil),    // 12: user.GetRegionResp
	(*GetSellPowerReq)(nil),  // 13: user.GetSellPowerReq
	(*GetSellPowerResp)(nil), // 14: user.GetSellPowerResp
}
var file_proto_user_proto_depIdxs = []int32{
	11, // 0: user.GetRegionResp.list:type_name -> user.RegionItem
	0,  // 1: user.User.Register:input_type -> user.RegisterReq
	2,  // 2: user.User.Login:input_type -> user.LoginReq
	4,  // 3: user.User.Captcha:input_type -> user.CaptchaReq
	6,  // 4: user.User.UserInfo:input_type -> user.UserInfoReq
	8,  // 5: user.User.ChangeInfo:input_type -> user.ChangeInfoReq
	10, // 6: user.User.GetRegion:input_type -> user.GetRegionReq
	13, // 7: user.User.GetSellPower:input_type -> user.GetSellPowerReq
	1,  // 8: user.User.Register:output_type -> user.RegisterResp
	3,  // 9: user.User.Login:output_type -> user.LoginResp
	5,  // 10: user.User.Captcha:output_type -> user.CaptchaResp
	7,  // 11: user.User.UserInfo:output_type -> user.UserInfoResp
	9,  // 12: user.User.ChangeInfo:output_type -> user.ChangeInfoResp
	12, // 13: user.User.GetRegion:output_type -> user.GetRegionResp
	14, // 14: user.User.GetSellPower:output_type -> user.GetSellPowerResp
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_user_proto_init() }
func file_proto_user_proto_init() {
	if File_proto_user_proto != nil {
		return
	}
	file_proto_user_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_user_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_proto_goTypes,
		DependencyIndexes: file_proto_user_proto_depIdxs,
		MessageInfos:      file_proto_user_proto_msgTypes,
	}.Build()
	File_proto_user_proto = out.File
	file_proto_user_proto_goTypes = nil
	file_proto_user_proto_depIdxs = nil
}
